package com.skyconnect.vista; 

import com.skyconnect.controlador.ControladorAeropuerto;
import com.skyconnect.modelo.Aeropuerto;

public class BuscarVueloView extends javax.swing.JPanel {
    private ControladorAeropuerto controladorAeropuerto;
    /**
     * Creates new form BuscarVueloView
     */
    private javax.swing.ButtonGroup grupoTipoVuelo;
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public BuscarVueloView(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        grupoTipoVuelo = new javax.swing.ButtonGroup();
        grupoTipoVuelo.add(radBtnIda);
        grupoTipoVuelo.add(radBtnIdaVuelta);
        
        controladorAeropuerto = new ControladorAeropuerto();
        cargarAeropuertos();
        
        //Deshabilita "Fecha de retorno" al escoger Solo IDA 
        jdtFechaRetorno.setEnabled(false);
    }
    //Muestra los aeropuertos cargados
    private void cargarAeropuertos() {
        cmbxOrigen.removeAllItems();
        cmbxDestino.removeAllItems();
        //Controla el listado de Ciudades en el apartado de Destino
        for (Aeropuerto a : controladorAeropuerto.getAeropuertos()) {
        String ciudad = a.getCiudad().trim();

            if ("Quito".equalsIgnoreCase(ciudad)) {
                cmbxOrigen.addItem(ciudad);
                } else {
                cmbxDestino.addItem(ciudad);
            }
        }
        cmbxOrigen.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        radBtnIdaVuelta = new javax.swing.JRadioButton();
        radBtnIda = new javax.swing.JRadioButton();
        btnOrigen = new javax.swing.JLabel();
        cmbxOrigen = new javax.swing.JComboBox<>();
        btnDestino = new javax.swing.JLabel();
        cmbxDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jbtnSiguienteBuscarVuelo = new javax.swing.JButton();
        jdtFechaViaje = new com.toedter.calendar.JDateChooser();
        jdtFechaRetorno = new com.toedter.calendar.JDateChooser();
        btnInSesion1 = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tercera Edad (mayores a 65 años): ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radBtnIdaVuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radBtnIdaVuelta.setText("Ida y vuelta ");
        radBtnIdaVuelta.addActionListener(this::radBtnIdaVueltaActionPerformed);
        jPanel1.add(radBtnIdaVuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 141, 121, 21));

        radBtnIda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radBtnIda.setText("Solo Ida");
        radBtnIda.addActionListener(this::radBtnIdaActionPerformed);
        jPanel1.add(radBtnIda, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 139, 98, -1));

        btnOrigen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOrigen.setText("ORIGEN:");
        jPanel1.add(btnOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 182, 126, 24));

        cmbxOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quito", "" }));
        cmbxOrigen.setAutoscrolls(true);
        cmbxOrigen.setName(""); // NOI18N
        cmbxOrigen.addActionListener(this::cmbxOrigenActionPerformed);
        jPanel1.add(cmbxOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 212, 237, 44));

        btnDestino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDestino.setText("DESTINO:");
        jPanel1.add(btnDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 184, 75, -1));

        cmbxDestino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una ciudad", "Guayaquil", "Cuenca", "Galápagos", "Bogotá", "Ciudad de Panamá", "Miami", "Madrid" }));
        cmbxDestino.setToolTipText("");
        cmbxDestino.addActionListener(this::cmbxDestinoActionPerformed);
        jPanel1.add(cmbxDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 212, 244, 44));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha de Viaje:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 315, 120, 16));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de Retorno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 313, 136, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Ecuador $ (USD) ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 29, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 197, 72));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("¿Quiénes Vuelan?");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Adultos (entre 12 a 64 años) : ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Niños (entre 3 a 11 años): ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tercera Edad (mayores a 65 años): ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Personas con discapacidad:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jSpinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 262, -1, -1));

        jbtnSiguienteBuscarVuelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSiguienteBuscarVuelo.setText("Siguiente");
        jbtnSiguienteBuscarVuelo.addActionListener(this::jbtnSiguienteBuscarVueloActionPerformed);
        jPanel1.add(jbtnSiguienteBuscarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 476, 124, -1));

        jdtFechaViaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jdtFechaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 351, 203, 31));

        jdtFechaRetorno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(jdtFechaRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 351, 189, 31));

        btnInSesion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInSesion1.setText("Iniciar Sesion");
        btnInSesion1.addActionListener(this::btnInSesion1ActionPerformed);
        jPanel1.add(btnInSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 26, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnIdaVueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnIdaVueltaActionPerformed
        jdtFechaRetorno.setEnabled(true);
    }//GEN-LAST:event_radBtnIdaVueltaActionPerformed

    private void radBtnIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnIdaActionPerformed
        jdtFechaRetorno.setEnabled(false);
        jdtFechaRetorno.setDate(null);
    }//GEN-LAST:event_radBtnIdaActionPerformed

    private void cmbxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxOrigenActionPerformed

    private void jbtnSiguienteBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSiguienteBuscarVueloActionPerformed
        // Verifica que el usuario haya seleccionado un tipo de vuelo antes de continuar
       if (radBtnIda.isSelected()) {
       mainFrame.mostrarVista("VUELOS IDA");
       return;
       }

        if (radBtnIdaVuelta.isSelected()) {
        mainFrame.mostrarVista("VUELOS IDA Y VUELTA");
        return;
    }       
    }//GEN-LAST:event_jbtnSiguienteBuscarVueloActionPerformed

    private void btnInSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInSesion1ActionPerformed

    private void cmbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDestino;
    private javax.swing.JButton btnInSesion1;
    private javax.swing.JLabel btnOrigen;
    private javax.swing.JComboBox<String> cmbxDestino;
    private javax.swing.JComboBox<String> cmbxOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JButton jbtnSiguienteBuscarVuelo;
    private com.toedter.calendar.JDateChooser jdtFechaRetorno;
    private com.toedter.calendar.JDateChooser jdtFechaViaje;
    private javax.swing.JRadioButton radBtnIda;
    private javax.swing.JRadioButton radBtnIdaVuelta;
    // End of variables declaration//GEN-END:variables
}
