package com.skyconnect.vista; 

import java.text.SimpleDateFormat;
import java.util.Date;
import com.skyconnect.controlador.ControladorAeropuerto;
import com.skyconnect.controlador.ControladorBusqueda;
import com.skyconnect.controlador.ControladorDescuentos;
import com.skyconnect.modelo.Aeropuerto;
import javax.swing.JOptionPane;

    public class BuscarVueloView extends javax.swing.JPanel {
        //Controladores necesarios en esta clase
        private ControladorAeropuerto controladorAeropuerto;
        private ControladorBusqueda controladorBusqueda;
        private ControladorDescuentos controladorDescuentos;
        private javax.swing.ButtonGroup grupoTipoVuelo;
        private MainFrame mainFrame;
    
        private String origen;
        private String destino;
        private String fechaViaje;
        private String fechaRetorno;
    
    
    /**
     * Creates new form BuscarVueloView
     * @param mainFrame
     * @param controladorBusqueda
     * @param controladorDescuentos
     */
  
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public BuscarVueloView(MainFrame mainFrame, ControladorBusqueda controladorBusqueda, ControladorDescuentos controladorDescuentos) {
        this.mainFrame = mainFrame;
        this.controladorBusqueda = controladorBusqueda;
        this.controladorDescuentos = new ControladorDescuentos();
        
        initComponents();
        jdtFechaRetorno.setEnabled(false);
        
        java.net.URL imgURL = getClass().getResource("/imagenes/BuscarVueloView.jpg");
        if (imgURL != null) {
            jLabelBuscarVuelo.setIcon(new javax.swing.ImageIcon(imgURL));
        }
        
        grupoTipoVuelo = new javax.swing.ButtonGroup();
        grupoTipoVuelo.add(radBtnIda);
        grupoTipoVuelo.add(radBtnIdaVuelta);
        
        controladorAeropuerto = new ControladorAeropuerto();
        cargarAeropuertos();
        
        //Deshabilita "Fecha de retorno" al escoger Solo IDA 
        jdtFechaRetorno.setEnabled(false);
    }
    
    //Muestra los aeropuertos disponibles iterando en una lista
    private void cargarAeropuertos(){
        cmbxOrigen.removeAllItems();
        cmbxDestino.removeAllItems();
        //Itera en el listado de aeropuertos y muestra la ciudad de los mismos
        for (Aeropuerto a : controladorAeropuerto.getAeropuertos()) {
        String ciudad = a.getCiudad().trim();
        //Lista todos los aeropuertos para origen y destino
                cmbxOrigen.addItem(ciudad);
                cmbxDestino.addItem(ciudad);
        }
    }

    public ControladorDescuentos getControladorDescuentos() {
        return controladorDescuentos;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerTerceraEdad = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerNinios = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerAdultos = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerPDiscapacidad = new javax.swing.JSpinner();
        jbtnSiguienteBuscarVuelo = new javax.swing.JButton();
        btnInSesion1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdtFechaViaje = new com.toedter.calendar.JDateChooser();
        jdtFechaRetorno = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        radBtnIdaVuelta = new javax.swing.JRadioButton();
        radBtnIda = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btnOrigen = new javax.swing.JLabel();
        cmbxOrigen = new javax.swing.JComboBox<>();
        cmbxDestino = new javax.swing.JComboBox<>();
        btnDestino = new javax.swing.JLabel();
        jLabelBuscarVuelo = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tercera Edad (mayores a 65 años): ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ecuador $ (USD) ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, -1, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("¿Quiénes Vuelan?");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setText("Adultos (entre 12 a 64 años) : ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 302, -1));

        jSpinnerTerceraEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerTerceraEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 79, 27));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setText("Niños (entre 2 a 11 años): ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 261, -1));

        jSpinnerNinios.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerNinios, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 79, 27));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setText("Tercera Edad (mayores a 65 años): ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jSpinnerAdultos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerAdultos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 79, 28));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Personas con discapacidad:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 304, -1));

        jSpinnerPDiscapacidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel2.add(jSpinnerPDiscapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 79, 27));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 480, 470, 260));

        jbtnSiguienteBuscarVuelo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnSiguienteBuscarVuelo.setText("Siguiente");
        jbtnSiguienteBuscarVuelo.addActionListener(this::jbtnSiguienteBuscarVueloActionPerformed);
        jPanel1.add(jbtnSiguienteBuscarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 790, 200, -1));

        btnInSesion1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnInSesion1.setText("Iniciar Sesion");
        btnInSesion1.addActionListener(this::btnInSesion1ActionPerformed);
        jPanel1.add(btnInSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 100, -1, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("Fecha de Retorno:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 290, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setText("Fecha de Salida:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 23, 240, 40));

        jdtFechaViaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(jdtFechaViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 74, 300, 49));

        jdtFechaRetorno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(jdtFechaRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 74, 280, 49));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 820, 170));

        jPanel4.setOpaque(false);

        radBtnIdaVuelta.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        radBtnIdaVuelta.setText("Ida y vuelta ");
        radBtnIdaVuelta.addActionListener(this::radBtnIdaVueltaActionPerformed);

        radBtnIda.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        radBtnIda.setText("Solo Ida");
        radBtnIda.addActionListener(this::radBtnIdaActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(radBtnIdaVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(radBtnIda, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnIdaVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radBtnIda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 600, 110));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrigen.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        btnOrigen.setText("ORIGEN:");
        jPanel5.add(btnOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 126, 24));

        cmbxOrigen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quito", "" }));
        cmbxOrigen.setAutoscrolls(true);
        cmbxOrigen.setName(""); // NOI18N
        cmbxOrigen.addActionListener(this::cmbxOrigenActionPerformed);
        jPanel5.add(cmbxOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 460, 60));

        cmbxDestino.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una ciudad", "Guayaquil", "Cuenca", "Galápagos", "Bogotá", "Ciudad de Panamá", "Miami", "Madrid" }));
        cmbxDestino.setToolTipText("");
        cmbxDestino.addActionListener(this::cmbxDestinoActionPerformed);
        jPanel5.add(cmbxDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 420, 60));

        btnDestino.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        btnDestino.setText("DESTINO:");
        jPanel5.add(btnDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 240, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 1360, 160));

        jLabelBuscarVuelo.setText("jLabel5");
        jPanel1.add(jLabelBuscarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1700, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnIdaVueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnIdaVueltaActionPerformed
        jdtFechaRetorno.setEnabled(true);
    }//GEN-LAST:event_radBtnIdaVueltaActionPerformed

    private void radBtnIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnIdaActionPerformed
        jdtFechaRetorno.setEnabled(false);
        jdtFechaRetorno.setDate(null);
    }//GEN-LAST:event_radBtnIdaActionPerformed

    private void cmbxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxOrigenActionPerformed
        
    }//GEN-LAST:event_cmbxOrigenActionPerformed

    private void jbtnSiguienteBuscarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSiguienteBuscarVueloActionPerformed
        
        //Obtener datos de los spinners
        int adultos = (int) jSpinnerAdultos.getValue();      // Adultos
        int ninios = (int) jSpinnerNinios.getValue();       // Niños
        int terceraEdad = (int) jSpinnerTerceraEdad.getValue();  // Tercera Edad
        int discapacidad = (int) jSpinnerPDiscapacidad.getValue(); // Discapacidad

        //Al menos debe viajar uno
        if ((adultos + ninios + terceraEdad + discapacidad) == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione al menos un pasajero.", "Sin pasajeros", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Obtener datos de los componentes
        this.origen = cmbxOrigen.getSelectedItem().toString();
        this.destino = cmbxDestino.getSelectedItem().toString();
        
        //Lógica de fechas a String
        Date fechaViajeTemp = jdtFechaViaje.getDate();
        if (fechaViajeTemp != null) {
        SimpleDateFormat fFSalida = new SimpleDateFormat("yyyy-MM-dd");
        this.fechaViaje = fFSalida.format(fechaViajeTemp);
        }

        Date fechaRetornoTemp = jdtFechaRetorno.getDate();
        if (fechaRetornoTemp != null) {
        SimpleDateFormat fFRetorno = new SimpleDateFormat("yyyy-MM-dd");
        this.fechaRetorno = fFRetorno.format(fechaRetornoTemp);
        }
        
        //Pasa las elecciones del usuario a variables en el Controlador
        controladorBusqueda.setCriteriosBusqueda(origen, destino, fechaViaje, fechaRetorno);
        
        // 1. Enviamos la ciudad de origen al Controlador de Descuentos
        if (controladorDescuentos != null) {
            controladorDescuentos.setCiudadOrigen(this.origen);
        }

        // 2. Preparamos la "Cola de Espera" en la pantalla de Registro
        if (mainFrame != null) {
            RegistroPasajeroView registroView = mainFrame.getRegistroPasajeroView();
            // Le pasamos cuántos de cada tipo hay para que arme la fila
            registroView.configurarPasajeros(adultos, ninios, terceraEdad, discapacidad);
        }

        //Cambiamos la vista según el tipo de vuelo seleccionado
            if(radBtnIda.isSelected()){
                //No vuelve a instanciar VueloIDAView, sino que obtiene la ventana creada antes
                VueloIDAView vueloIDAView = mainFrame.getVueloIDAView();
                // Entregamos el controlador lleno de pasajeros a la siguiente vista
                vueloIDAView.setControladorPasajeros(this.controladorDescuentos);
                //Con los datos obtenidos, vueloIDAView muestra los vuelos
                vueloIDAView.cargarDatosYBuscar();
                mainFrame.mostrarVista("VUELOS IDA");
            } else if(radBtnIdaVuelta.isSelected()){
                //No vuelve a instanciar VueloIDAVUELTA, sino que obtiene la ventana creada antes
                VueloIDAVUELTAView vueloIDAVUELTAView = mainFrame.getVueloIDAVUELTAView();
                
                
                // Entregamos el controlador lleno de pasajeros a la siguiente vista
                vueloIDAVUELTAView.setControladorPasajeros(this.controladorDescuentos);
                
                
                //Con los datos obtenidos, vueloIDAView muestra los vuelos
                vueloIDAVUELTAView.cargarDatosYBuscar();
                mainFrame.mostrarVista("VUELOS IDA Y VUELTA");
            }
    }//GEN-LAST:event_jbtnSiguienteBuscarVueloActionPerformed

    private void btnInSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInSesion1ActionPerformed

    private void cmbxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxDestinoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDestino;
    private javax.swing.JButton btnInSesion1;
    private javax.swing.JLabel btnOrigen;
    private javax.swing.JComboBox<String> cmbxDestino;
    private javax.swing.JComboBox<String> cmbxOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBuscarVuelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JSpinner jSpinnerAdultos;
    private javax.swing.JSpinner jSpinnerNinios;
    private javax.swing.JSpinner jSpinnerPDiscapacidad;
    private javax.swing.JSpinner jSpinnerTerceraEdad;
    private javax.swing.JButton jbtnSiguienteBuscarVuelo;
    private com.toedter.calendar.JDateChooser jdtFechaRetorno;
    private com.toedter.calendar.JDateChooser jdtFechaViaje;
    private javax.swing.JRadioButton radBtnIda;
    private javax.swing.JRadioButton radBtnIdaVuelta;
    // End of variables declaration//GEN-END:variables
}
