package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorUsuario;

public class CreacionUsuarioView extends javax.swing.JPanel {
    private ControladorUsuario controlador; 

    /**
     * Creates new form CreacionUsuarioView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public CreacionUsuarioView(MainFrame mainFrame) {
        this.mainFrame = mainFrame; 
        initComponents();
        controlador = new ControladorUsuario(mainFrame);
        java.net.URL imgURL = getClass().getResource("/imagenes/CreacionUsuario.jpg");
        if (imgURL != null) {
         
            jLabelCrear.setIcon(new javax.swing.ImageIcon(imgURL));
    }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfNombreCreacionUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtfApellidoCreacionUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfCorreoCreacionUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpasswordCrearContraseña = new javax.swing.JPasswordField();
        btnRegistrarseCreacionUsuario = new javax.swing.JButton();
        jLabelCrear = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 31, 227, -1));

        txtfNombreCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtfNombreCreacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 90, 336, 47));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setText("Apellido:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 149, -1, -1));

        txtfApellidoCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfApellidoCreacionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoCreacionUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtfApellidoCreacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 193, 336, 52));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("Correo electrónico:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 273, 276, -1));

        txtfCorreoCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtfCorreoCreacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 323, 336, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 417, 209, -1));

        jpasswordCrearContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpasswordCrearContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordCrearContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(jpasswordCrearContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 473, 336, 50));

        btnRegistrarseCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrarseCreacionUsuario.setText("Registrarse");
        btnRegistrarseCreacionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseCreacionUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarseCreacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 260, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 750, 660));

        jLabelCrear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jade\\OneDrive\\Documentos\\NetBeansProjects\\SkyConnect\\src\\main\\java\\resources\\imagenes\\CreacionUsuario.jpg")); // NOI18N
        jLabelCrear.setText("jLabel5");
        jPanel1.add(jLabelCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1690, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfApellidoCreacionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoCreacionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoCreacionUsuarioActionPerformed

    private void jpasswordCrearContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordCrearContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordCrearContraseñaActionPerformed

    private void btnRegistrarseCreacionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseCreacionUsuarioActionPerformed
        // Esta vista captura los datos del usuario y delega el proceso de registro
        // al ControladorUsuario, manteniendo la separación de responsabilidades del patrón MVC.

        String nombre = txtfNombreCreacionUsuario.getText().trim();
        String apellido = txtfApellidoCreacionUsuario.getText().trim();
        String correo = txtfCorreoCreacionUsuario.getText().trim();
        String clave = new String(jpasswordCrearContraseña.getPassword());

        controlador.registrarUsuario(nombre, apellido, correo, clave);
    }//GEN-LAST:event_btnRegistrarseCreacionUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarseCreacionUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCrear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpasswordCrearContraseña;
    private javax.swing.JTextField txtfApellidoCreacionUsuario;
    private javax.swing.JTextField txtfCorreoCreacionUsuario;
    private javax.swing.JTextField txtfNombreCreacionUsuario;
    // End of variables declaration//GEN-END:variables
}
