package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorUsuario;

public class CreacionUsuarioView extends javax.swing.JPanel {
    private ControladorUsuario controlador; 

    /**
     * Creates new form CreacionUsuarioView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public CreacionUsuarioView(MainFrame mainFrame) {
        this.mainFrame = mainFrame; 
        initComponents();
        controlador = new ControladorUsuario(mainFrame);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarseCreacionUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfNombreCreacionUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtfApellidoCreacionUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfCorreoCreacionUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpasswordCrearContraseña = new javax.swing.JPasswordField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarseCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegistrarseCreacionUsuario.setText("Registrarse");
        btnRegistrarseCreacionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseCreacionUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarseCreacionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 260, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText("Nombre:");

        txtfNombreCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setText("Apellido:");

        txtfApellidoCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfApellidoCreacionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoCreacionUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("Correo electrónico:");

        txtfCorreoCreacionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("Contraseña:");

        jpasswordCrearContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpasswordCrearContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordCrearContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpasswordCrearContraseña)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtfCorreoCreacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfApellidoCreacionUsuario)
                            .addComponent(txtfNombreCreacionUsuario)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfNombreCreacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfApellidoCreacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfCorreoCreacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jpasswordCrearContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 630, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfApellidoCreacionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoCreacionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoCreacionUsuarioActionPerformed

    private void jpasswordCrearContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordCrearContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordCrearContraseñaActionPerformed

    private void btnRegistrarseCreacionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseCreacionUsuarioActionPerformed
        // Esta vista captura los datos del usuario y delega el proceso de registro
        // al ControladorUsuario, manteniendo la separación de responsabilidades del patrón MVC.

        String nombre = txtfNombreCreacionUsuario.getText().trim();
        String apellido = txtfApellidoCreacionUsuario.getText().trim();
        String correo = txtfCorreoCreacionUsuario.getText().trim();
        String clave = new String(jpasswordCrearContraseña.getPassword());

        controlador.registrarUsuario(nombre, apellido, correo, clave);
    }//GEN-LAST:event_btnRegistrarseCreacionUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarseCreacionUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpasswordCrearContraseña;
    private javax.swing.JTextField txtfApellidoCreacionUsuario;
    private javax.swing.JTextField txtfCorreoCreacionUsuario;
    private javax.swing.JTextField txtfNombreCreacionUsuario;
    // End of variables declaration//GEN-END:variables
}
