package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorReserva;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class EquipajeExtraView extends javax.swing.JPanel {
    private final MainFrame mainFrame;
    private ControladorReserva controladorReserva;
    private ButtonGroup grupoTipoEquipaje;
    
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public EquipajeExtraView(MainFrame mainFrame, ControladorReserva controladorReserva) {
        this.mainFrame = mainFrame;
        this.controladorReserva = controladorReserva;
        initComponents();
        configurarGrupoRadio();
    }
     // Agrupa los radio buttons
    private void configurarGrupoRadio() {
        grupoTipoEquipaje = new ButtonGroup();
        grupoTipoEquipaje.add(jrdbEquipajeFacturadoExtra);
        grupoTipoEquipaje.add(jrdbBolsoManoExtra);
    }
    // Botón SI: registrar y limpiar
    // Botón NO: registrar y avanzar
    //Envía los datos al controlador
    // Envía los datos al controlador y maneja validaciones
    private boolean registrarEquipaje() {
    //Recoge la información del equipaje 
    try {
        String propietario = txtNombrePropietarioExtra.getText().trim();
        double peso = Double.parseDouble(txtFPesoEquipajeExtra.getText());

        String tipo;
        if (jrdbEquipajeFacturadoExtra.isSelected()) {
            tipo = "FACTURADO";
        } else if (jrdbBolsoManoExtra.isSelected()) {
            tipo = "MANO";
        } else {
            throw new IllegalArgumentException("Seleccione un tipo de equipaje");
        }

        // Llamamos al controlador y guardamos los datos
        controladorReserva.registrarEquipajeExtra(tipo, propietario, peso);
        guardarDatosEquipaje(propietario, peso, tipo);  // Guardamos en el archivo


        return true;

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Peso inválido",
                "Error",
                JOptionPane.WARNING_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.WARNING_MESSAGE);
    }
    return false;
}
    // Guardar los datos en un archivo de texto
    private void guardarDatosEquipaje(String propietario, double peso, String tipo) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("equipajes.txt", true))) {
            writer.write("Propietario: " + propietario + ", Peso: " + peso + " kg, Tipo: " + tipo);
            writer.newLine();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    // Limpia los campos del formulario
    private void limpiarFormulario() {
        txtNombrePropietarioExtra.setText("");
        txtFPesoEquipajeExtra.setText("");
        grupoTipoEquipaje.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jrdbEquipajeFacturadoExtra = new javax.swing.JRadioButton();
        jrdbBolsoManoExtra = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombrePropietarioExtra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFPesoEquipajeExtra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnRegistrarOtroEquipaje = new javax.swing.JButton();
        jbtNoRegistrarOtroEquipaje = new javax.swing.JButton();
        jbtnGuardarRegistroEquipaje = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del equipaje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 48))); // NOI18N

        jrdbEquipajeFacturadoExtra.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jrdbEquipajeFacturadoExtra.setText("Equipaje facturado ");
        jrdbEquipajeFacturadoExtra.addActionListener(this::jrdbEquipajeFacturadoExtraActionPerformed);

        jrdbBolsoManoExtra.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jrdbBolsoManoExtra.setText("Bolso de mano");
        jrdbBolsoManoExtra.addActionListener(this::jrdbBolsoManoExtraActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setText("Nombre del propietario: ");

        txtNombrePropietarioExtra.addActionListener(this::txtNombrePropietarioExtraActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setText("Peso del equipaje: ");

        txtFPesoEquipajeExtra.addActionListener(this::txtFPesoEquipajeExtraActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("¿Desea registrar otro equipaje?");

        jbtnRegistrarOtroEquipaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnRegistrarOtroEquipaje.setText("Si");
        jbtnRegistrarOtroEquipaje.addActionListener(this::jbtnRegistrarOtroEquipajeActionPerformed);

        jbtNoRegistrarOtroEquipaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtNoRegistrarOtroEquipaje.setText("No");
        jbtNoRegistrarOtroEquipaje.addActionListener(this::jbtNoRegistrarOtroEquipajeActionPerformed);

        jbtnGuardarRegistroEquipaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnGuardarRegistroEquipaje.setText("GUARDAR");
        jbtnGuardarRegistroEquipaje.addActionListener(this::jbtnGuardarRegistroEquipajeActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombrePropietarioExtra)
                            .addComponent(txtFPesoEquipajeExtra)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jrdbEquipajeFacturadoExtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(jrdbBolsoManoExtra)))
                .addGap(91, 91, 91))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnRegistrarOtroEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(jbtNoRegistrarOtroEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnGuardarRegistroEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdbBolsoManoExtra)
                    .addComponent(jrdbEquipajeFacturadoExtra))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtNombrePropietarioExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFPesoEquipajeExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbtnGuardarRegistroEquipaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNoRegistrarOtroEquipaje)
                    .addComponent(jbtnRegistrarOtroEquipaje))
                .addGap(65, 65, 65))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 900, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrdbEquipajeFacturadoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbEquipajeFacturadoExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdbEquipajeFacturadoExtraActionPerformed

    private void txtNombrePropietarioExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePropietarioExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePropietarioExtraActionPerformed

    private void jbtNoRegistrarOtroEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNoRegistrarOtroEquipajeActionPerformed
        if (registrarEquipaje()) {
        mainFrame.mostrarVista("PAGO");
        }
    }//GEN-LAST:event_jbtNoRegistrarOtroEquipajeActionPerformed

    private void jrdbBolsoManoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbBolsoManoExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdbBolsoManoExtraActionPerformed

    private void jbtnRegistrarOtroEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarOtroEquipajeActionPerformed
        if (registrarEquipaje()) {
            limpiarFormulario(); // Limpiamos los campos para agregar otro equipaje
        }
    }//GEN-LAST:event_jbtnRegistrarOtroEquipajeActionPerformed

    private void txtFPesoEquipajeExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPesoEquipajeExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPesoEquipajeExtraActionPerformed

    private void jbtnGuardarRegistroEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarRegistroEquipajeActionPerformed
        // Recoge la información del equipaje
        if (registrarEquipaje()) {
            JOptionPane.showMessageDialog(this, "Guardado con éxito ✔️");
        }
    }//GEN-LAST:event_jbtnGuardarRegistroEquipajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtNoRegistrarOtroEquipaje;
    private javax.swing.JButton jbtnGuardarRegistroEquipaje;
    private javax.swing.JButton jbtnRegistrarOtroEquipaje;
    private javax.swing.JRadioButton jrdbBolsoManoExtra;
    private javax.swing.JRadioButton jrdbEquipajeFacturadoExtra;
    private javax.swing.JTextField txtFPesoEquipajeExtra;
    private javax.swing.JTextField txtNombrePropietarioExtra;
    // End of variables declaration//GEN-END:variables
}
