package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorReserva;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class EquipajeExtraView extends javax.swing.JPanel {
    private final MainFrame mainFrame;
    private ControladorReserva controladorReserva;
    private ButtonGroup grupoTipoEquipaje;
    
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public EquipajeExtraView(MainFrame mainFrame, ControladorReserva controladorReserva) {
        this.mainFrame = mainFrame;
        this.controladorReserva = controladorReserva;
        initComponents();
        configurarGrupoRadio();
    }
     // Agrupa los radio buttons
    private void configurarGrupoRadio() {
        grupoTipoEquipaje = new ButtonGroup();
        grupoTipoEquipaje.add(jrdbEquipajeFacturadoExtra);
        grupoTipoEquipaje.add(jrdbBolsoManoExtra);
    }
    // Botón SI: registrar y limpiar
    // Botón NO: registrar y avanzar
    //Envía los datos al controlador
    // Envía los datos al controlador y maneja validaciones
    private boolean registrarEquipaje() {
    try {
        String propietario = txtNombrePropietarioExtra.getText().trim();
        double peso = Double.parseDouble(txtFPesoEquipajeExtra.getText());

        String tipo;
        if (jrdbEquipajeFacturadoExtra.isSelected()) {
            tipo = "FACTURADO";
        } else if (jrdbBolsoManoExtra.isSelected()) {
            tipo = "MANO";
        } else {
            throw new IllegalArgumentException("Seleccione un tipo de equipaje");
        }

        // 👉 SOLO LLAMAS AL CONTROLADOR
        controladorReserva.registrarEquipajeExtra(tipo, propietario, peso);

        return true;

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Peso inválido",
                "Error",
                JOptionPane.WARNING_MESSAGE);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.WARNING_MESSAGE);
    }
    return false;
}
    // Limpia los campos del formulario
    private void limpiarFormulario() {
        txtNombrePropietarioExtra.setText("");
        txtFPesoEquipajeExtra.setText("");
        grupoTipoEquipaje.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jrdbEquipajeFacturadoExtra = new javax.swing.JRadioButton();
        jrdbBolsoManoExtra = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombrePropietarioExtra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFPesoEquipajeExtra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbtnRegistrarOtroEquipaje = new javax.swing.JButton();
        jbtNoRegistrarOtroEquipaje = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del equipaje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jrdbEquipajeFacturadoExtra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrdbEquipajeFacturadoExtra.setText("Equipaje facturado ");
        jrdbEquipajeFacturadoExtra.addActionListener(this::jrdbEquipajeFacturadoExtraActionPerformed);

        jrdbBolsoManoExtra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jrdbBolsoManoExtra.setText("Bolso de mano");
        jrdbBolsoManoExtra.addActionListener(this::jrdbBolsoManoExtraActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre del propietario: ");

        txtNombrePropietarioExtra.addActionListener(this::txtNombrePropietarioExtraActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Peso del equipaje: ");

        txtFPesoEquipajeExtra.addActionListener(this::txtFPesoEquipajeExtraActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("¿Desea registrar otro equipaje?");

        jbtnRegistrarOtroEquipaje.setText("Si");
        jbtnRegistrarOtroEquipaje.addActionListener(this::jbtnRegistrarOtroEquipajeActionPerformed);

        jbtNoRegistrarOtroEquipaje.setText("No");
        jbtNoRegistrarOtroEquipaje.addActionListener(this::jbtNoRegistrarOtroEquipajeActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jrdbEquipajeFacturadoExtra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jrdbBolsoManoExtra)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePropietarioExtra)
                            .addComponent(txtFPesoEquipajeExtra, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnRegistrarOtroEquipaje)
                        .addGap(60, 60, 60)
                        .addComponent(jbtNoRegistrarOtroEquipaje))
                    .addComponent(jLabel3))
                .addGap(121, 121, 121))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdbBolsoManoExtra)
                    .addComponent(jrdbEquipajeFacturadoExtra))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombrePropietarioExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFPesoEquipajeExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnRegistrarOtroEquipaje)
                    .addComponent(jbtNoRegistrarOtroEquipaje))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrdbEquipajeFacturadoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbEquipajeFacturadoExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdbEquipajeFacturadoExtraActionPerformed

    private void txtNombrePropietarioExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePropietarioExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePropietarioExtraActionPerformed

    private void jbtNoRegistrarOtroEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNoRegistrarOtroEquipajeActionPerformed
        if (registrarEquipaje()) {
        mainFrame.mostrarVista("PagoView");
        }
    }//GEN-LAST:event_jbtNoRegistrarOtroEquipajeActionPerformed

    private void jrdbBolsoManoExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbBolsoManoExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdbBolsoManoExtraActionPerformed

    private void jbtnRegistrarOtroEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarOtroEquipajeActionPerformed
        if (registrarEquipaje()) {
        JOptionPane.showMessageDialog(this, "Equipaje registrado ✔️");
        limpiarFormulario();
        }
    }//GEN-LAST:event_jbtnRegistrarOtroEquipajeActionPerformed

    private void txtFPesoEquipajeExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPesoEquipajeExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPesoEquipajeExtraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtNoRegistrarOtroEquipaje;
    private javax.swing.JButton jbtnRegistrarOtroEquipaje;
    private javax.swing.JRadioButton jrdbBolsoManoExtra;
    private javax.swing.JRadioButton jrdbEquipajeFacturadoExtra;
    private javax.swing.JTextField txtFPesoEquipajeExtra;
    private javax.swing.JTextField txtNombrePropietarioExtra;
    // End of variables declaration//GEN-END:variables
}
