package com.skyconnect.vista;

import com.skyconnect.modelo.Factura;
import javax.swing.JTextArea;

public class FacturaView extends javax.swing.JPanel {
    private Factura factura; // El modelo Factura
    private MainFrame mainFrame;
    private String metodoDePago; // Para almacenar el método de pago

    // Constructor que inicializa la vista con los datos de la factura.
    public FacturaView(MainFrame mainFrame, Factura factura, String metodoDePago) {
        this.mainFrame = mainFrame;
        this.factura = factura;
        this.metodoDePago = metodoDePago; // Guardamos el método de pago
        initComponents();  // NetBeans genera este método, no lo modifiques
        mostrarFactura(); // Llamamos al método para mostrar la factura.
    
        java.net.URL imgURL = getClass().getResource("/imagenes/Factura.jpg");

        if (imgURL != null) {
            jLabelFactura.setIcon(new javax.swing.ImageIcon(imgURL));
}

    }
    // Método para mostrar los datos de la factura en un JTextArea.
    private void mostrarFactura() {
        // Formato de factura
        StringBuilder facturaTexto = new StringBuilder();
        facturaTexto.append("************* FACTURA DE RESERVA DE VUELO *************\n");
        facturaTexto.append("-------------------------------------------------------\n");
        facturaTexto.append("Origen: " + factura.getOrigen() + "\n");
        facturaTexto.append("Destino: " + factura.getDestino() + "\n");
        facturaTexto.append("Fecha: " + factura.getFecha() + "\n");
        facturaTexto.append("Horario: " + factura.getHorario() + "\n");
        facturaTexto.append("N° Pasajeros: " + factura.getNumeroPasajeros() + "\n");
        facturaTexto.append("-------------------------------------------------------\n");
        facturaTexto.append("Precio Base: $" + factura.getPrecioBase() + "\n");
        facturaTexto.append("Impuestos: $" + factura.getImpuestos() + "\n");
        facturaTexto.append("Adicionales: $" + factura.getAdicionales() + "\n");
        facturaTexto.append("Descuentos: $" + factura.getDescuentos() + "\n");
        facturaTexto.append("-------------------------------------------------------\n");
        facturaTexto.append("Total: $" + factura.getTotal() + "\n");
        facturaTexto.append("-------------------------------------------------------\n");

        // Método de pago
        facturaTexto.append("Método de Pago: " + metodoDePago + "\n");

        // Mensaje de agradecimiento
        facturaTexto.append("\nGracias por preferirnos. ¡UN BUEN VIAJE!\n");
        facturaTexto.append("-------------------------------------------------------\n");

        // Mostrar en el JTextArea
        txtFacturaFinal.setText(facturaTexto.toString());  // Usa solo txtFacturaFinal, el que fue generado en initComponents
    }

    // Método para regresar a la vista anterior (ej. PagoView)
    private void regresar() {
        mainFrame.mostrarVista("PAGO"); // Redirige a la vista de pago
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFacturaFinal = new javax.swing.JTextArea();
        jLabelFactura = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36))); // NOI18N
        jPanel2.setOpaque(false);

        txtFacturaFinal.setColumns(20);
        txtFacturaFinal.setRows(5);
        jScrollPane1.setViewportView(txtFacturaFinal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        jLabelFactura.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jade\\OneDrive\\Documentos\\NetBeansProjects\\SkyConnect\\src\\main\\java\\resources\\imagenes\\Factura.jpg")); // NOI18N
        jLabelFactura.setText("jLabel1");
        jPanel1.add(jLabelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1690, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFactura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtFacturaFinal;
    // End of variables declaration//GEN-END:variables
    }
