package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorUsuario;
import javax.swing.JOptionPane;

public class IniciarSesionView extends javax.swing.JPanel {
    private ControladorUsuario controladorUsuario;
    /**
     * Creates new form IniciarSesionView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public IniciarSesionView(MainFrame mainFrame,ControladorUsuario controladorUsuario) {
        this.mainFrame = mainFrame; 
        this.controladorUsuario = new ControladorUsuario();
        initComponents();
        
        java.net.URL imgURL = getClass().getResource("/imagenes/CreacionUsuario.jpg");
        if (imgURL != null) {
            jLabelIniciarSesion.setIcon(new javax.swing.ImageIcon(imgURL));
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngresarUsuarioIniciarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtfUsuarioIniciarSesion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpasswordIngreseContraseñaIniciarS = new javax.swing.JPasswordField();
        jLabelIniciarSesion = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarUsuarioIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIngresarUsuarioIniciarSesion.setText("Ingresar");
        btnIngresarUsuarioIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarUsuarioIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarUsuarioIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 740, 270, 42));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("Correo electrónico:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 172, -1, -1));

        txtfUsuarioIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfUsuarioIniciarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(txtfUsuarioIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 228, 474, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("Contraseña:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 344, -1, -1));

        jpasswordIngreseContraseñaIniciarS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpasswordIngreseContraseñaIniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordIngreseContraseñaIniciarSActionPerformed(evt);
            }
        });
        jPanel2.add(jpasswordIngreseContraseñaIniciarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 388, 474, 62));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 720, 610));

        jLabelIniciarSesion.setText("jLabel1");
        jPanel1.add(jLabelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1706, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfUsuarioIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfUsuarioIniciarSesionActionPerformed

    private void btnIngresarUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarUsuarioIniciarSesionActionPerformed
        // Obtiene los datos ingresados por el usuario desde la vista
        String usuario = txtfUsuarioIniciarSesion.getText().trim();
        String clave = new String(jpasswordIngreseContraseñaIniciarS.getPassword());

        //Comprueba las credenciales del usuario con las guardadas en archivos
        if(controladorUsuario.iniciarSesion(usuario, clave)){
            JOptionPane.showMessageDialog(this, "Inicio de sesion exitoso.", "" ,JOptionPane.INFORMATION_MESSAGE);
            mainFrame.mostrarVista("REGISTRO");
        } else {
            JOptionPane.showMessageDialog(this, "Inicio de sesion fallido.", "" ,JOptionPane.WARNING_MESSAGE);
        }

            //controladorLogin.loginExitoso();
    }//GEN-LAST:event_btnIngresarUsuarioIniciarSesionActionPerformed

    private void jpasswordIngreseContraseñaIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordIngreseContraseñaIniciarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordIngreseContraseñaIniciarSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarUsuarioIniciarSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelIniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpasswordIngreseContraseñaIniciarS;
    private javax.swing.JTextField txtfUsuarioIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
