package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorLogin;
import javax.swing.JOptionPane;

public class IniciarSesionView extends javax.swing.JPanel {
    private ControladorLogin controladorLogin;
    /**
     * Creates new form IniciarSesionView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public IniciarSesionView(MainFrame mainFrame) {
        this.mainFrame = mainFrame; 
        initComponents();
        controladorLogin = new ControladorLogin(mainFrame);
    }
    
    private void mostrarMensaje(String mensaje, int tipo) {
    JOptionPane.showMessageDialog(
        this,
        mensaje,
        "Información",
        tipo
        );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngresarUsuarioIniciarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtfUsuarioIniciarSesion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpasswordIngreseContraseñaIniciarS = new javax.swing.JPasswordField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarUsuarioIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIngresarUsuarioIniciarSesion.setText("Ingresar");
        btnIngresarUsuarioIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarUsuarioIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarUsuarioIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 270, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setText("Correo electrónico:");

        txtfUsuarioIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfUsuarioIniciarSesionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("Contraseña:");

        jpasswordIngreseContraseñaIniciarS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpasswordIngreseContraseñaIniciarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordIngreseContraseñaIniciarSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfUsuarioIniciarSesion)
                            .addComponent(jpasswordIngreseContraseñaIniciarS))
                        .addGap(91, 91, 91))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 315, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtfUsuarioIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpasswordIngreseContraseñaIniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 720, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfUsuarioIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfUsuarioIniciarSesionActionPerformed

    private void btnIngresarUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarUsuarioIniciarSesionActionPerformed
        // Obtiene los datos ingresados por el usuario desde la vista
        String usuario = txtfUsuarioIniciarSesion.getText().trim();
        String clave = new String(jpasswordIngreseContraseñaIniciarS.getPassword());

        // Valida campos vacíos
        if (!controladorLogin.validarCampos(usuario, clave)) {
            mostrarMensaje("Debe completar todos los campos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Verifica las credenciales ingresadas por el usuario.
        // Si la autenticación falla, se muestra un mensaje de error y se detiene el flujo.
        // Si es correcta, el controlador se encarga de redirigir a la siguiente vista.
        if (!controladorLogin.autenticar(usuario, clave)) {
        mostrarMensaje("Usuario o contraseña incorrectos", JOptionPane.ERROR_MESSAGE);
        return;
    }

    controladorLogin.loginExitoso();
    }//GEN-LAST:event_btnIngresarUsuarioIniciarSesionActionPerformed

    private void jpasswordIngreseContraseñaIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordIngreseContraseñaIniciarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordIngreseContraseñaIniciarSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarUsuarioIniciarSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpasswordIngreseContraseñaIniciarS;
    private javax.swing.JTextField txtfUsuarioIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
