package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorLogin;
import javax.swing.JOptionPane;

public class IniciarSesionView extends javax.swing.JPanel {
    private ControladorLogin controladorLogin;
    /**
     * Creates new form IniciarSesionView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public IniciarSesionView(MainFrame mainFrame) {
        this.mainFrame = mainFrame; 
        initComponents();
        controladorLogin = new ControladorLogin(mainFrame);
    }
    
    private void mostrarMensaje(String mensaje, int tipo) {
    JOptionPane.showMessageDialog(
        this,
        mensaje,
        "Información",
        tipo
        );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtfUsuarioIniciarSesion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIngresarUsuarioIniciarSesion = new javax.swing.JButton();
        jpasswordIngreseContraseñaIniciarS = new javax.swing.JPasswordField();

        txtfUsuarioIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtfUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfUsuarioIniciarSesionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Correo electrónico:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña:");

        btnIngresarUsuarioIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIngresarUsuarioIniciarSesion.setText("Ingresar");
        btnIngresarUsuarioIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresarUsuarioIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarUsuarioIniciarSesionActionPerformed(evt);
            }
        });

        jpasswordIngreseContraseñaIniciarS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(btnIngresarUsuarioIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpasswordIngreseContraseñaIniciarS)
                    .addComponent(jLabel3)
                    .addComponent(txtfUsuarioIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfUsuarioIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpasswordIngreseContraseñaIniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnIngresarUsuarioIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfUsuarioIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfUsuarioIniciarSesionActionPerformed

    private void btnIngresarUsuarioIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarUsuarioIniciarSesionActionPerformed
        // Obtiene los datos ingresados por el usuario desde la vista
        String usuario = txtfUsuarioIniciarSesion.getText().trim();
        String clave = new String(jpasswordIngreseContraseñaIniciarS.getPassword());

        // Valida campos vacíos
        if (!controladorLogin.validarCampos(usuario, clave)) {
            mostrarMensaje("Debe completar todos los campos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Verifica las credenciales ingresadas por el usuario.
        // Si la autenticación falla, se muestra un mensaje de error y se detiene el flujo.
        // Si es correcta, el controlador se encarga de redirigir a la siguiente vista.
        if (!controladorLogin.autenticar(usuario, clave)) {
        mostrarMensaje("Usuario o contraseña incorrectos", JOptionPane.ERROR_MESSAGE);
        return;
    }

    controladorLogin.loginExitoso();
    }//GEN-LAST:event_btnIngresarUsuarioIniciarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarUsuarioIniciarSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jpasswordIngreseContraseñaIniciarS;
    private javax.swing.JTextField txtfUsuarioIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
