/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.skyconnect.vista;
import java.awt.CardLayout;


/**
 *
 * @author mateo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private CardLayout cardLayout;
    
    // ===== VISTAS (UNA SOLA INSTANCIA) =====
    private InicioView inicioView;
    private LoginView loginView;
    private BuscarVueloView buscarVueloView;
    private ClaseVueloView claseVueloView;
    private AsientosView asientosView;
    private EquipajeExtraView equipajeExtraView;
    private IniciarSesionView iniciarSesionView;
    private CreacionUsuarioView creacionUsuarioView;
    private PagoView pagoView;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        inicializarVistas();
    }
    private void inicializarVistas() {

    cardLayout = (CardLayout) PanelContenedor.getLayout();
    
    // Crear vistas (UNA SOLA VEZ)
        inicioView = new InicioView();
        buscarVueloView = new BuscarVueloView();
        claseVueloView = new ClaseVueloView();
        asientosView = new AsientosView();
        equipajeExtraView = new EquipajeExtraView();
        loginView = new LoginView();
        iniciarSesionView = new IniciarSesionView();
        creacionUsuarioView = new CreacionUsuarioView();
        pagoView = new PagoView();
        
        // Agregar vistas al CardLayout
        PanelContenedor.add(inicioView, "INICIO");
        PanelContenedor.add(buscarVueloView, "BUSCAR");
        PanelContenedor.add(claseVueloView, "CLASE");
        PanelContenedor.add(asientosView, "ASIENTOS");
        PanelContenedor.add(equipajeExtraView, "EQUIPAJE");
        PanelContenedor.add(loginView, "LOGIN");
        PanelContenedor.add(iniciarSesionView, "INICIAR");
        PanelContenedor.add(creacionUsuarioView, "CREAR");
        PanelContenedor.add(pagoView, "PAGO");
        
        //Vista inicial 
        mostrarVista("INICIO");
}
    
   public void mostrarVista(String nombreVista) {
    cardLayout.show(PanelContenedor, nombreVista);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    // End of variables declaration//GEN-END:variables
}
