package com.skyconnect.vista;
import com.skyconnect.controlador.ControladorPago;
import com.skyconnect.controlador.ControladorReserva;
import com.skyconnect.modelo.Reserva;
import java.awt.CardLayout;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private CardLayout cardLayout;
    private ControladorReserva controladorReserva;
    private ControladorPago controladorPago;
    
    // ===== VISTAS (UNA SOLA INSTANCIA) =====
    private InicioView inicioView;
    private LoginView loginView;
    private BuscarVueloView buscarVueloView;
    private VueloIDAView vueloIDAView; 
    private VueloIDAVUELTAView vueloIDAVUELTAView;
    private VueloIVUELTAView vueloIVUELTAView; 
    private ClaseVueloView claseVueloView;
    private AsientosView asientosView;
    private EquipajeExtraView equipajeExtraView;
    private IniciarSesionView iniciarSesionView;
    private CreacionUsuarioView creacionUsuarioView;
    private PagoView pagoView;
    private TarjetaView tarjetaView; 
    private PayPalView payPalView; 
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        inicializarVistas();
    }
    private void inicializarVistas() {

    cardLayout = (CardLayout) PanelContenedor.getLayout();

    //CONTROLADORES (UNA SOLA INSTANCIA)
    controladorReserva = new ControladorReserva();
    // Crear la reserva antes de instanciar el controladorPago
    Reserva reserva = controladorReserva.getReserva();  // Obtener la reserva de controladorReserva
    controladorPago = new ControladorPago(reserva);

    //VISTAS
    inicioView = new InicioView(this);
    buscarVueloView = new BuscarVueloView(this);
    vueloIDAView = new VueloIDAView(this);
    vueloIDAVUELTAView = new VueloIDAVUELTAView(this);
    vueloIVUELTAView = new VueloIVUELTAView(this);
    claseVueloView = new ClaseVueloView(this);
    asientosView = new AsientosView(this, controladorReserva);
    equipajeExtraView = new EquipajeExtraView(this, controladorReserva);
    loginView = new LoginView(this);
    iniciarSesionView = new IniciarSesionView(this);
    creacionUsuarioView = new CreacionUsuarioView(this);
    pagoView = new PagoView(this, controladorPago);
    tarjetaView = new TarjetaView(this, controladorPago);
    payPalView = new PayPalView(this, controladorPago);

    //CARD LAYOUT
    PanelContenedor.add(inicioView, "INICIO");
    PanelContenedor.add(buscarVueloView, "BUSCAR");
    PanelContenedor.add(vueloIDAView, "VUELOS IDA");
    PanelContenedor.add(vueloIDAVUELTAView, "VUELOS IDA Y VUELTA");
    PanelContenedor.add(vueloIVUELTAView, "VUELOS VUELTA");
    PanelContenedor.add(claseVueloView, "CLASE");
    PanelContenedor.add(asientosView, "ASIENTOS");
    PanelContenedor.add(equipajeExtraView, "EQUIPAJE");
    PanelContenedor.add(loginView, "LOGIN");
    PanelContenedor.add(iniciarSesionView, "INICIAR");
    PanelContenedor.add(creacionUsuarioView, "CREAR");
    PanelContenedor.add(pagoView, "PAGO");
    PanelContenedor.add(tarjetaView, "TARJETA");
    PanelContenedor.add(payPalView, "PAYPAL");

    mostrarVista("INICIO");
}
    
   public void mostrarVista(String nombreVista) {
    cardLayout.show(PanelContenedor, nombreVista);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    // End of variables declaration//GEN-END:variables
}
