package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorPago;

public class PagoView extends javax.swing.JPanel {
    private ControladorPago controladorPago; 
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    public PagoView(MainFrame mainFrame, ControladorPago controladorPago) {
        this.mainFrame = mainFrame;
        this.controladorPago = controladorPago;
        initComponents();
        cargarResumen();
        java.net.URL imgURL = getClass().getResource("/imagenes/pago.jpg");

        if (imgURL != null) {
            // Usamos el nombre que me indicaste: pago (suponiendo que es jLabelPago o pago)
            jLabelPago.setIcon(new javax.swing.ImageIcon(imgURL));
    }
    }
    //Imprime el resumen de compra 
    private void cargarResumen() {
    txtFResumenOrigen.setText(controladorPago.getOrigen());
    txtFResumenDestino.setText(controladorPago.getDestino());
    txtFResumenFecha.setText(controladorPago.getFecha());
    txtFResumenHorario.setText(controladorPago.getHorario());

    txtFResumenNPasajeros.setText(String.valueOf(controladorPago.getNumeroPasajeros()));
    txtFResumenAsientos.setText(String.join(", ", controladorPago.getAsientos()));
    txtFResumenPrecioBase.setText(String.valueOf(controladorPago.getPrecioBase()));
    txtFResumenImpuestos.setText(String.valueOf(controladorPago.getImpuestos()));
    txtFResumenAdicionales.setText(String.valueOf(controladorPago.getAdicionales()));
    txtFResumenDescuentos.setText(String.valueOf(controladorPago.getDescuentos()));
    txtFResumenTotalPagar.setText(String.valueOf(controladorPago.getTotal()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFResumenDestino = new javax.swing.JTextField();
        txtFResumenOrigen = new javax.swing.JTextField();
        txtFResumenFecha = new javax.swing.JTextField();
        txtFResumenPrecioBase = new javax.swing.JTextField();
        txtFResumenNPasajeros = new javax.swing.JTextField();
        txtFResumenAsientos = new javax.swing.JTextField();
        txtFResumenTotalPagar = new javax.swing.JTextField();
        txtFResumenImpuestos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFResumenHorario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFResumenAdicionales = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFResumenDescuentos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnPagarPayPal = new javax.swing.JButton();
        jbtnPagarTarjeta1 = new javax.swing.JButton();
        jLabelPago = new javax.swing.JLabel();

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(this::jTextField6ActionPerformed);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen de compra ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Orígen: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Destino: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Fecha: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("N° Pasajeros: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Asientos: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Precio base total: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Impuestos: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Total a pagar:");

        txtFResumenDestino.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenDestino.setEnabled(false);
        txtFResumenDestino.addActionListener(this::txtFResumenDestinoActionPerformed);

        txtFResumenOrigen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenOrigen.setEnabled(false);
        txtFResumenOrigen.addActionListener(this::txtFResumenOrigenActionPerformed);

        txtFResumenFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenFecha.setEnabled(false);
        txtFResumenFecha.addActionListener(this::txtFResumenFechaActionPerformed);

        txtFResumenPrecioBase.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenPrecioBase.setEnabled(false);
        txtFResumenPrecioBase.addActionListener(this::txtFResumenPrecioBaseActionPerformed);

        txtFResumenNPasajeros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenNPasajeros.setEnabled(false);
        txtFResumenNPasajeros.addActionListener(this::txtFResumenNPasajerosActionPerformed);

        txtFResumenAsientos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenAsientos.setEnabled(false);
        txtFResumenAsientos.addActionListener(this::txtFResumenAsientosActionPerformed);

        txtFResumenTotalPagar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenTotalPagar.setEnabled(false);
        txtFResumenTotalPagar.addActionListener(this::txtFResumenTotalPagarActionPerformed);

        txtFResumenImpuestos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenImpuestos.setEnabled(false);
        txtFResumenImpuestos.addActionListener(this::txtFResumenImpuestosActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Horario:");

        txtFResumenHorario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenHorario.setEnabled(false);
        txtFResumenHorario.addActionListener(this::txtFResumenHorarioActionPerformed);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setText("Adicionales:");

        txtFResumenAdicionales.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenAdicionales.setEnabled(false);
        txtFResumenAdicionales.addActionListener(this::txtFResumenAdicionalesActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Descuentos: ");

        txtFResumenDescuentos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFResumenDescuentos.setEnabled(false);
        txtFResumenDescuentos.addActionListener(this::txtFResumenDescuentosActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(10, 10, 10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFResumenDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(txtFResumenOrigen)
                            .addComponent(txtFResumenFecha)
                            .addComponent(txtFResumenNPasajeros)
                            .addComponent(txtFResumenAsientos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFResumenHorario, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFResumenTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(txtFResumenDescuentos)
                            .addComponent(txtFResumenPrecioBase, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFResumenImpuestos)
                            .addComponent(txtFResumenAdicionales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenNPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFResumenAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 600, 650));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Método de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 36))); // NOI18N
        jPanel3.setOpaque(false);

        jbtnPagarPayPal.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbtnPagarPayPal.setText("PayPal");
        jbtnPagarPayPal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPagarPayPal.addActionListener(this::jbtnPagarPayPalActionPerformed);

        jbtnPagarTarjeta1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jbtnPagarTarjeta1.setText("Tarjeta");
        jbtnPagarTarjeta1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPagarTarjeta1.addActionListener(this::jbtnPagarTarjeta1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jbtnPagarTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jbtnPagarPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPagarTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPagarPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 480, 220));

        jLabelPago.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jade\\OneDrive\\Documentos\\NetBeansProjects\\SkyConnect\\src\\main\\java\\resources\\imagenes\\Pago.jpg")); // NOI18N
        jLabelPago.setText("jLabel10");
        jPanel1.add(jLabelPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFResumenDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenDestinoActionPerformed

    private void txtFResumenOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenOrigenActionPerformed

    private void txtFResumenFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenFechaActionPerformed

    private void txtFResumenPrecioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenPrecioBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenPrecioBaseActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void txtFResumenNPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenNPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenNPasajerosActionPerformed

    private void txtFResumenAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenAsientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenAsientosActionPerformed

    private void txtFResumenTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenTotalPagarActionPerformed

    private void txtFResumenImpuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenImpuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenImpuestosActionPerformed

    private void txtFResumenHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenHorarioActionPerformed

    private void txtFResumenAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenAdicionalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenAdicionalesActionPerformed

    private void jbtnPagarPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagarPayPalActionPerformed
        mainFrame.mostrarVista("PAYPAL");
    }//GEN-LAST:event_jbtnPagarPayPalActionPerformed

    private void jbtnPagarTarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagarTarjeta1ActionPerformed
        mainFrame.mostrarVista("TARJETA");
    }//GEN-LAST:event_jbtnPagarTarjeta1ActionPerformed

    private void txtFResumenDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenDescuentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenDescuentosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton jbtnPagarPayPal;
    private javax.swing.JButton jbtnPagarTarjeta1;
    private javax.swing.JTextField txtFResumenAdicionales;
    private javax.swing.JTextField txtFResumenAsientos;
    private javax.swing.JTextField txtFResumenDescuentos;
    private javax.swing.JTextField txtFResumenDestino;
    private javax.swing.JTextField txtFResumenFecha;
    private javax.swing.JTextField txtFResumenHorario;
    private javax.swing.JTextField txtFResumenImpuestos;
    private javax.swing.JTextField txtFResumenNPasajeros;
    private javax.swing.JTextField txtFResumenOrigen;
    private javax.swing.JTextField txtFResumenPrecioBase;
    private javax.swing.JTextField txtFResumenTotalPagar;
    // End of variables declaration//GEN-END:variables
}
