package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorPago;

public class PagoView extends javax.swing.JPanel {
    private ControladorPago controladorPago; 
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    public PagoView(MainFrame mainFrame, ControladorPago controladorPago) {
        this.mainFrame = mainFrame;
        this.controladorPago = controladorPago;
        initComponents();
        cargarResumen();
    }
    //Imprime el resumen de compra 
    private void cargarResumen() {
    txtFResumenOrigen.setText(controladorPago.getOrigen());
    txtFResumenDestino.setText(controladorPago.getDestino());
    txtFResumenFecha.setText(controladorPago.getFecha());
    txtFResumenHorario.setText(controladorPago.getHorario());

    txtFResumenNPasajeros.setText(String.valueOf(controladorPago.getNumeroPasajeros()));
    txtFResumenAsientos.setText(String.join(", ", controladorPago.getAsientos()));
    txtFResumenPrecioBase.setText(String.valueOf(controladorPago.getPrecioBase()));
    txtFResumenImpuestos.setText(String.valueOf(controladorPago.getImpuestos()));
    txtFResumenAdicionales.setText(String.valueOf(controladorPago.getAdicionales()));
    txtFResumenDescuentos.setText(String.valueOf(controladorPago.getDescuentos()));
    txtFResumenTotalPagar.setText(String.valueOf(controladorPago.getTotal()));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFResumenDestino = new javax.swing.JTextField();
        txtFResumenOrigen = new javax.swing.JTextField();
        txtFResumenFecha = new javax.swing.JTextField();
        txtFResumenPrecioBase = new javax.swing.JTextField();
        txtFResumenNPasajeros = new javax.swing.JTextField();
        txtFResumenAsientos = new javax.swing.JTextField();
        txtFResumenTotalPagar = new javax.swing.JTextField();
        txtFResumenImpuestos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFResumenHorario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFResumenAdicionales = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFResumenDescuentos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnPagarPayPal = new javax.swing.JButton();
        jbtnPagarTarjeta1 = new javax.swing.JButton();

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jTextField6.setEnabled(false);
        jTextField6.addActionListener(this::jTextField6ActionPerformed);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen de compra ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Orígen: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Destino: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("N° Pasajeros: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Asientos: ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Precio base total: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Impuestos: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Total a pagar:");

        txtFResumenDestino.setEnabled(false);
        txtFResumenDestino.addActionListener(this::txtFResumenDestinoActionPerformed);

        txtFResumenOrigen.setEnabled(false);
        txtFResumenOrigen.addActionListener(this::txtFResumenOrigenActionPerformed);

        txtFResumenFecha.setEnabled(false);
        txtFResumenFecha.addActionListener(this::txtFResumenFechaActionPerformed);

        txtFResumenPrecioBase.setEnabled(false);
        txtFResumenPrecioBase.addActionListener(this::txtFResumenPrecioBaseActionPerformed);

        txtFResumenNPasajeros.setEnabled(false);
        txtFResumenNPasajeros.addActionListener(this::txtFResumenNPasajerosActionPerformed);

        txtFResumenAsientos.setEnabled(false);
        txtFResumenAsientos.addActionListener(this::txtFResumenAsientosActionPerformed);

        txtFResumenTotalPagar.setEnabled(false);
        txtFResumenTotalPagar.addActionListener(this::txtFResumenTotalPagarActionPerformed);

        txtFResumenImpuestos.setEnabled(false);
        txtFResumenImpuestos.addActionListener(this::txtFResumenImpuestosActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Horario:");

        txtFResumenHorario.setEnabled(false);
        txtFResumenHorario.addActionListener(this::txtFResumenHorarioActionPerformed);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Adicionales:");

        txtFResumenAdicionales.setEnabled(false);
        txtFResumenAdicionales.addActionListener(this::txtFResumenAdicionalesActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Descuentos: ");

        txtFResumenDescuentos.setEnabled(false);
        txtFResumenDescuentos.addActionListener(this::txtFResumenDescuentosActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(296, 298, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(txtFResumenDescuentos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtFResumenHorario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFResumenDestino)
                                    .addComponent(txtFResumenOrigen)
                                    .addComponent(txtFResumenFecha)
                                    .addComponent(txtFResumenNPasajeros)
                                    .addComponent(txtFResumenAsientos, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFResumenAdicionales, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(txtFResumenTotalPagar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(txtFResumenPrecioBase))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(txtFResumenImpuestos)))
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenNPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFResumenAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenImpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFResumenTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Método de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jbtnPagarPayPal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPagarPayPal.setText("PayPal");
        jbtnPagarPayPal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPagarPayPal.addActionListener(this::jbtnPagarPayPalActionPerformed);

        jbtnPagarTarjeta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPagarTarjeta1.setText("Tarjeta");
        jbtnPagarTarjeta1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnPagarTarjeta1.addActionListener(this::jbtnPagarTarjeta1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jbtnPagarTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnPagarPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPagarTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPagarPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFResumenDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenDestinoActionPerformed

    private void txtFResumenOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenOrigenActionPerformed

    private void txtFResumenFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenFechaActionPerformed

    private void txtFResumenPrecioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenPrecioBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenPrecioBaseActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void txtFResumenNPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenNPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenNPasajerosActionPerformed

    private void txtFResumenAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenAsientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenAsientosActionPerformed

    private void txtFResumenTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenTotalPagarActionPerformed

    private void txtFResumenImpuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenImpuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenImpuestosActionPerformed

    private void txtFResumenHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenHorarioActionPerformed

    private void txtFResumenAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenAdicionalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenAdicionalesActionPerformed

    private void jbtnPagarPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagarPayPalActionPerformed
        mainFrame.mostrarVista("PAYPAL");
    }//GEN-LAST:event_jbtnPagarPayPalActionPerformed

    private void jbtnPagarTarjeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagarTarjeta1ActionPerformed
        mainFrame.mostrarVista("TARJETA");
    }//GEN-LAST:event_jbtnPagarTarjeta1ActionPerformed

    private void txtFResumenDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFResumenDescuentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFResumenDescuentosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton jbtnPagarPayPal;
    private javax.swing.JButton jbtnPagarTarjeta1;
    private javax.swing.JTextField txtFResumenAdicionales;
    private javax.swing.JTextField txtFResumenAsientos;
    private javax.swing.JTextField txtFResumenDescuentos;
    private javax.swing.JTextField txtFResumenDestino;
    private javax.swing.JTextField txtFResumenFecha;
    private javax.swing.JTextField txtFResumenHorario;
    private javax.swing.JTextField txtFResumenImpuestos;
    private javax.swing.JTextField txtFResumenNPasajeros;
    private javax.swing.JTextField txtFResumenOrigen;
    private javax.swing.JTextField txtFResumenPrecioBase;
    private javax.swing.JTextField txtFResumenTotalPagar;
    // End of variables declaration//GEN-END:variables
}
