package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorPago;
import javax.swing.JOptionPane;

public class PayPalView extends javax.swing.JPanel {
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
     private MainFrame mainFrame;
    private ControladorPago controladorPago; 
    
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    public PayPalView(MainFrame mainFrame, ControladorPago controladorPago) {
        this.mainFrame = mainFrame;
        this.controladorPago = controladorPago; 
        initComponents();
        registrarEventos();
    }

    // Registro de eventos de los botones
    private void registrarEventos() {
        jButton1.addActionListener(e -> procesarPago());
        jbtnAceptarPagoPayPal.addActionListener(e -> procesarPagoConPayPal());
        JbtnCancelarPagoPayPal.addActionListener(e -> cancelarPago());
    }
    /**
     * Método para procesar el pago (general)
     * Este método puede delegar el pago específico a través del controlador según el tipo de pago
     */
    private void procesarPago() {
        // Aquí podemos verificar el tipo de pago seleccionado por el usuario
        // Como solo tenemos la lógica de PayPal, procedemos con eso.
        String correo = txtFIniciarSesionPayPal.getText().trim();
        String contrasena = txtFContraseñaPayPal.getText().trim();

        // Validación simple de los campos
        if (correo.isEmpty() || contrasena.isEmpty()) {
            mostrarMensajeError("Los campos de correo y contraseña son obligatorios.");
            return;
        }

        // Delegar la lógica del pago al controlador de pago (si fuera necesario, puedes agregar un tipo de pago)
        controladorPago.procesarPagoPayPal(correo, contrasena);

        // Mostrar mensaje de éxito
        mostrarMensajeExito("Pago realizado con éxito a través de PayPal.");
    }

    // Método que procesa el pago con PayPal (concretamente)
    private void procesarPagoConPayPal() {
        String correo = txtFIniciarSesionPayPal.getText().trim();
        String contrasena = txtFContraseñaPayPal.getText().trim();

        // Validación simple de los campos
        if (correo.isEmpty() || contrasena.isEmpty()) {
            mostrarMensajeError("Los campos de correo y contraseña son obligatorios.");
            return;
        }

        // Delegamos la lógica del pago al controlador
        controladorPago.procesarPagoPayPal(correo, contrasena);

        // Mostrar mensaje de éxito
        mostrarMensajeExito("Pago realizado con éxito a través de PayPal.");
    }

    // Método que cancela el pago y regresa a la vista anterior
    private void cancelarPago() {
        mainFrame.mostrarVista("PAGO");
    }

    // Método que muestra un mensaje de error
    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Método que muestra un mensaje de éxito
    private void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtFContraseñaPayPal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFIniciarSesionPayPal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFPagoFinalPayPal = new javax.swing.JTextField();
        jbtnAceptarPagoPayPal = new javax.swing.JButton();
        JbtnCancelarPagoPayPal = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PayPal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 48))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Confirmar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 240, -1));

        txtFContraseñaPayPal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFContraseñaPayPal.addActionListener(this::txtFContraseñaPayPalActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Correo Electrónico ");

        txtFIniciarSesionPayPal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Contraseña");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFContraseñaPayPal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFIniciarSesionPayPal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFIniciarSesionPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(txtFContraseñaPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 560, 440));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 690, 710));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel3.setText("Se procederá con el pago de: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel4.setText("USD");

        txtFPagoFinalPayPal.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtFPagoFinalPayPal.setEnabled(false);
        txtFPagoFinalPayPal.addActionListener(this::txtFPagoFinalPayPalActionPerformed);

        jbtnAceptarPagoPayPal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnAceptarPagoPayPal.setText("Aceptar");
        jbtnAceptarPagoPayPal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JbtnCancelarPagoPayPal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JbtnCancelarPagoPayPal.setText("Cancelar");
        JbtnCancelarPagoPayPal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbtnCancelarPagoPayPal.addActionListener(this::JbtnCancelarPagoPayPalActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jbtnAceptarPagoPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JbtnCancelarPagoPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFPagoFinalPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtFPagoFinalPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAceptarPagoPayPal)
                    .addComponent(JbtnCancelarPagoPayPal))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 620, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1658, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFContraseñaPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFContraseñaPayPalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFContraseñaPayPalActionPerformed

    private void JbtnCancelarPagoPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCancelarPagoPayPalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtnCancelarPagoPayPalActionPerformed

    private void txtFPagoFinalPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPagoFinalPayPalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPagoFinalPayPalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnCancelarPagoPayPal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnAceptarPagoPayPal;
    private javax.swing.JTextField txtFContraseñaPayPal;
    private javax.swing.JTextField txtFIniciarSesionPayPal;
    private javax.swing.JTextField txtFPagoFinalPayPal;
    // End of variables declaration//GEN-END:variables
}
