package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorDescuentos;
import com.skyconnect.controlador.ControladorPasajeros;

public class RegistroPasajeroView extends javax.swing.JPanel {
    
    private ControladorDescuentos controladorDescuento;
    private ControladorPasajeros controladorPasajero;
    private MainFrame mainFrame;
    
    public RegistroPasajeroView(MainFrame mainFrame, ControladorDescuentos controladorDescuentos, ControladorPasajeros controladorPasajero) {
        this.mainFrame = mainFrame;
        this.controladorDescuento = new ControladorDescuentos();
        //this.controladorPasajero = new ControladorPasajeros();
        
        initComponents();
        
        java.net.URL imgURL = getClass().getResource("/imagenes/Boleto.jpg");
        if (imgURL != null) {
            jLabelRegistro.setIcon(new javax.swing.ImageIcon(imgURL));
        }
    }
    
    public void setControladorDescuentos(ControladorDescuentos controladorDescuento){
        this.controladorDescuento = controladorDescuento;
    }
    
    public void setControladorPasajeros(ControladorPasajeros controladorPasajero){
        this.controladorPasajero = controladorPasajero;
    }
    
    //Getters y Setters
    public String getNombre() {return txtRegistroNombrePasajero.getText().trim();}
    public String getApellido() {return txtApellidoRegistroPasajero.getText().trim();}
    public String getCedula() {return txtCIRegistroPasajero1.getText().trim();}
    public String getPasaporte() {return txtPasaporteRegistroPasajero.getText().trim();}
    
    //Listener
    public void addBtnGuardarListener(java.awt.event.ActionListener listener) {
        jbtnGuardarRegistroPasajero.addActionListener(listener);
        jbtnGuardarRegistroPasajero.setActionCommand("Guardar");
    }

    public void addBtnSiguienteListener(java.awt.event.ActionListener listener) {
        jbtnSiguienteRegistroPasajero.addActionListener(listener);
        jbtnSiguienteRegistroPasajero.setActionCommand("Siguiente");
    }
    
    
    //metodo que limpia los campos
    public void limpiarCampos() {
        txtRegistroNombrePasajero.setText("");
        txtApellidoRegistroPasajero.setText("");
        txtCIRegistroPasajero1.setText("");
        txtPasaporteRegistroPasajero.setText("");
        txtRegistroNombrePasajero.requestFocus(); // Pone el cursor de nuevo en el nombre
    }
    
    // Método para actualizar el mensaje de qué pasajero se está registrando
    public void actualizarIdentificador(String tipo, int numero) {
        this.txtIdentificadorPasajero.setText("Pasajero: " + tipo + " " + numero);
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoRegistroPasajero = new javax.swing.JTextField();
        txtRegistroNombrePasajero = new javax.swing.JTextField();
        txtPasaporteRegistroPasajero = new javax.swing.JTextField();
        jbtnGuardarRegistroPasajero = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCIRegistroPasajero1 = new javax.swing.JTextField();
        txtIdentificadorPasajero = new javax.swing.JLabel();
        jbtnSiguienteRegistroPasajero = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtObtenerNombreUsuario = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Información de Pasajeros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 48))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 210, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Apellido: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 210, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setText("Pasaporte:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 290, 43));

        txtApellidoRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoRegistroPasajero.addActionListener(this::txtApellidoRegistroPasajeroActionPerformed);
        jPanel2.add(txtApellidoRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 319, 50));

        txtRegistroNombrePasajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRegistroNombrePasajero.addActionListener(this::txtRegistroNombrePasajeroActionPerformed);
        jPanel2.add(txtRegistroNombrePasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 319, 50));

        txtPasaporteRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPasaporteRegistroPasajero.addActionListener(this::txtPasaporteRegistroPasajeroActionPerformed);
        jPanel2.add(txtPasaporteRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 320, 50));

        jbtnGuardarRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnGuardarRegistroPasajero.setText("Guardar");
        jbtnGuardarRegistroPasajero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnGuardarRegistroPasajero.addActionListener(this::jbtnGuardarRegistroPasajeroActionPerformed);
        jPanel2.add(jbtnGuardarRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 170, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Cédula:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 290, 43));

        txtCIRegistroPasajero1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCIRegistroPasajero1.addActionListener(this::txtCIRegistroPasajero1ActionPerformed);
        jPanel2.add(txtCIRegistroPasajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 320, 50));

        txtIdentificadorPasajero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdentificadorPasajero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtIdentificadorPasajero.setText("Pasajero: ");
        jPanel2.add(txtIdentificadorPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 490, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 820, 680));

        jbtnSiguienteRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnSiguienteRegistroPasajero.setText("Siguiente");
        jbtnSiguienteRegistroPasajero.addActionListener(this::jbtnSiguienteRegistroPasajeroActionPerformed);
        jPanel1.add(jbtnSiguienteRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 910, 220, 50));

        jLabelRegistro.setText("jLabel5");
        jPanel1.add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 1000));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 80, 40));

        txtObtenerNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtObtenerNombreUsuario.setEnabled(false);
        jPanel1.add(txtObtenerNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 190, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCIRegistroPasajero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIRegistroPasajero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIRegistroPasajero1ActionPerformed

    private void jbtnGuardarRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarRegistroPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGuardarRegistroPasajeroActionPerformed

    private void jbtnSiguienteRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSiguienteRegistroPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSiguienteRegistroPasajeroActionPerformed

    private void txtRegistroNombrePasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroNombrePasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroNombrePasajeroActionPerformed

    private void txtApellidoRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoRegistroPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoRegistroPasajeroActionPerformed

    private void txtPasaporteRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasaporteRegistroPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasaporteRegistroPasajeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnGuardarRegistroPasajero;
    private javax.swing.JButton jbtnSiguienteRegistroPasajero;
    private javax.swing.JTextField txtApellidoRegistroPasajero;
    private javax.swing.JTextField txtCIRegistroPasajero1;
    private javax.swing.JLabel txtIdentificadorPasajero;
    private javax.swing.JTextField txtObtenerNombreUsuario;
    private javax.swing.JTextField txtPasaporteRegistroPasajero;
    private javax.swing.JTextField txtRegistroNombrePasajero;
    // End of variables declaration//GEN-END:variables
}
