package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorDescuentos;
import com.skyconnect.controlador.ControladorPasajeros;
import com.skyconnect.modelo.Adulto;
import com.skyconnect.modelo.AdultoMayor;
import com.skyconnect.modelo.Discapacitado;
import com.skyconnect.modelo.Ninio;
import com.skyconnect.modelo.Pasajero;
import javax.swing.JOptionPane;

public class RegistroPasajeroView extends javax.swing.JPanel {
    
    private ControladorDescuentos controladorDescuento;
    private ControladorPasajeros controladorPasajero;
    private MainFrame mainFrame;
    // Una lista para recordar el orden: ["Adulto", "Adulto", "Niño", ...]
    private java.util.ArrayList<String> colaTiposPorRegistrar = new java.util.ArrayList<>();
    
    public RegistroPasajeroView(MainFrame mainFrame, ControladorDescuentos controladorDescuentos, ControladorPasajeros controladorPasajero) {
        this.mainFrame = mainFrame;
        this.controladorDescuento = controladorDescuentos;
        this.controladorPasajero =  controladorPasajero;
        
        initComponents();
        
        java.net.URL imgURL = getClass().getResource("/imagenes/Boleto.jpg");
        if (imgURL != null) {
            jLabelRegistro.setIcon(new javax.swing.ImageIcon(imgURL));
        }
    }
    
    public void setControladorDescuentos(ControladorDescuentos controladorDescuento){
        this.controladorDescuento = controladorDescuento;
    }
    
    public void setControladorPasajeros(ControladorPasajeros controladorPasajero){
        this.controladorPasajero = controladorPasajero;
    }
    
    //Getters y Setters
    public String getNombre() {return txtRegistroNombrePasajero.getText().trim();}
    public String getApellido() {return txtApellidoRegistroPasajero.getText().trim();}
    public String getCedula() {return txtCIRegistroPasajero1.getText().trim();}
    public String getPasaporte() {return txtPasaporteRegistroPasajero.getText().trim();}
    
    //Listener
    public void addBtnGuardarListener(java.awt.event.ActionListener listener) {
        jbtnGuardarRegistroPasajero.addActionListener(listener);
        jbtnGuardarRegistroPasajero.setActionCommand("Guardar");
    }

    public void addBtnSiguienteListener(java.awt.event.ActionListener listener) {
        jbtnSiguienteRegistroPasajero.addActionListener(listener);
        jbtnSiguienteRegistroPasajero.setActionCommand("Siguiente");
    }
    
    
    //metodo que limpia los campos
    public void limpiarCampos() {
        txtRegistroNombrePasajero.setText("");
        txtApellidoRegistroPasajero.setText("");
        txtCIRegistroPasajero1.setText("");
        txtPasaporteRegistroPasajero.setText("");
        txtRegistroNombrePasajero.requestFocus(); // Pone el cursor de nuevo en el nombre
    }
    
    // Este método recibe la lista de cantidades desde la pantalla de Búsqueda
    public void configurarPasajeros(int adultos, int ninios, int tercera, int discap) {
        colaTiposPorRegistrar.clear();
        
        // Llenamos la fila india
        for (int i = 0; i < adultos; i++) colaTiposPorRegistrar.add("Adulto");
        for (int i = 0; i < ninios; i++) colaTiposPorRegistrar.add("Niño");
        for (int i = 0; i < tercera; i++) colaTiposPorRegistrar.add("Tercera Edad");
        for (int i = 0; i < discap; i++) colaTiposPorRegistrar.add("Discapacitado");
        
        actualizarTitulo(); // Mostramos el primero
    }

    // Este método revisa la cola y actualiza el título y el ComboBox automáticamente
    private void actualizarTitulo() {
        if (!colaTiposPorRegistrar.isEmpty()) {
            String siguiente = colaTiposPorRegistrar.get(0);
            
            // Actualizamos el título visual
            txtIdentificadorPasajero.setText("Registrando: " + siguiente + " (Faltan: " + colaTiposPorRegistrar.size() + ")");
            
        } else {
            txtIdentificadorPasajero.setText("¡Todos los pasajeros registrados!");
            jbtnGuardarRegistroPasajero.setEnabled(false); // Bloqueamos guardar
            jbtnSiguienteRegistroPasajero.setEnabled(true); // Habilitamos Siguiente
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoRegistroPasajero = new javax.swing.JTextField();
        txtRegistroNombrePasajero = new javax.swing.JTextField();
        txtPasaporteRegistroPasajero = new javax.swing.JTextField();
        jbtnGuardarRegistroPasajero = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCIRegistroPasajero1 = new javax.swing.JTextField();
        txtIdentificadorPasajero = new javax.swing.JLabel();
        jbtnSiguienteRegistroPasajero = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtObtenerNombreUsuario = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Información de Pasajeros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 48))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 210, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setText("Apellido: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 210, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setText("Pasaporte:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 290, 43));

        txtApellidoRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoRegistroPasajero.addActionListener(this::txtApellidoRegistroPasajeroActionPerformed);
        jPanel2.add(txtApellidoRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 319, 50));

        txtRegistroNombrePasajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRegistroNombrePasajero.addActionListener(this::txtRegistroNombrePasajeroActionPerformed);
        jPanel2.add(txtRegistroNombrePasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 319, 50));

        txtPasaporteRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPasaporteRegistroPasajero.addActionListener(this::txtPasaporteRegistroPasajeroActionPerformed);
        jPanel2.add(txtPasaporteRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 320, 50));

        jbtnGuardarRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnGuardarRegistroPasajero.setText("Guardar");
        jbtnGuardarRegistroPasajero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnGuardarRegistroPasajero.addActionListener(this::jbtnGuardarRegistroPasajeroActionPerformed);
        jPanel2.add(jbtnGuardarRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 170, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Cédula:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 290, 43));

        txtCIRegistroPasajero1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCIRegistroPasajero1.addActionListener(this::txtCIRegistroPasajero1ActionPerformed);
        jPanel2.add(txtCIRegistroPasajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 320, 50));

        txtIdentificadorPasajero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdentificadorPasajero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtIdentificadorPasajero.setText("Pasajero: ");
        jPanel2.add(txtIdentificadorPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 490, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 820, 680));

        jbtnSiguienteRegistroPasajero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnSiguienteRegistroPasajero.setText("Siguiente");
        jbtnSiguienteRegistroPasajero.addActionListener(this::jbtnSiguienteRegistroPasajeroActionPerformed);
        jPanel1.add(jbtnSiguienteRegistroPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 910, 220, 50));

        jLabelRegistro.setText("jLabel5");
        jPanel1.add(jLabelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 1000));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, 80, 40));

        txtObtenerNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtObtenerNombreUsuario.setEnabled(false);
        jPanel1.add(txtObtenerNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 20, 190, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCIRegistroPasajero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIRegistroPasajero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIRegistroPasajero1ActionPerformed

    private void jbtnGuardarRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarRegistroPasajeroActionPerformed
    
        // 0. Seguridad
        if (colaTiposPorRegistrar.isEmpty()) return;

        // 1. Capturar datos
        String nombre = txtRegistroNombrePasajero.getText().trim();
        String apellido = txtApellidoRegistroPasajero.getText().trim();
        String cedula = txtCIRegistroPasajero1.getText().trim();
        String pasaporte = txtPasaporteRegistroPasajero.getText().trim();

        // 2. Validación
        if (nombre.isEmpty() || apellido.isEmpty() || cedula.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Llene campos obligatorios.");
            return;
        }

        // 3. Crear Objeto
        String tipoActual = colaTiposPorRegistrar.get(0); 
        Pasajero nuevoPasajero = null;

        if (tipoActual.equals("Adulto")) nuevoPasajero = new Adulto(nombre, apellido, cedula, pasaporte);
        else if (tipoActual.equals("Niño")) nuevoPasajero = new Ninio(nombre, apellido, cedula, pasaporte);
        else if (tipoActual.equals("Tercera Edad")) nuevoPasajero = new AdultoMayor(nombre, apellido, cedula, pasaporte);
        else if (tipoActual.equals("Discapacitado")) nuevoPasajero = new Discapacitado(nombre, apellido, cedula, pasaporte);

        // 4. Guardar y Avanzar
        if (nuevoPasajero != null && controladorPasajero != null) {
            
            if (controladorDescuento != null) {
                controladorDescuento.aplicarDescuento(nuevoPasajero);
            }

            controladorPasajero.agregarPasajero(nuevoPasajero);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Guardado: " + tipoActual);
            
            colaTiposPorRegistrar.remove(0); // Quitamos de la fila
            
            actualizarTitulo(); 
            limpiarCampos();
        }
        
    }//GEN-LAST:event_jbtnGuardarRegistroPasajeroActionPerformed

    private void jbtnSiguienteRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSiguienteRegistroPasajeroActionPerformed
        // TODO add your handling code here:
        // Solo dejamos pasar si la cola está vacía (todos registrados)
        if (colaTiposPorRegistrar.isEmpty()) {
            
            // 1. Obtener la vista de asientos
            AsientosView asientosView = mainFrame.getAsientosView(); 
            
            // 2. Pasarle el controlador lleno de gente
            asientosView.setControladorPasajeros(this.controladorPasajero);
            
            // 3. Mostrar la vista
            mainFrame.mostrarVista("ASIENTOS"); 
            
        } else {
             javax.swing.JOptionPane.showMessageDialog(this, "Aún faltan pasajeros por registrar (" + colaTiposPorRegistrar.size() + ")");
        }
    }//GEN-LAST:event_jbtnSiguienteRegistroPasajeroActionPerformed

    private void txtRegistroNombrePasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegistroNombrePasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegistroNombrePasajeroActionPerformed

    private void txtApellidoRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoRegistroPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoRegistroPasajeroActionPerformed

    private void txtPasaporteRegistroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasaporteRegistroPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasaporteRegistroPasajeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnGuardarRegistroPasajero;
    private javax.swing.JButton jbtnSiguienteRegistroPasajero;
    private javax.swing.JTextField txtApellidoRegistroPasajero;
    private javax.swing.JTextField txtCIRegistroPasajero1;
    private javax.swing.JLabel txtIdentificadorPasajero;
    private javax.swing.JTextField txtObtenerNombreUsuario;
    private javax.swing.JTextField txtPasaporteRegistroPasajero;
    private javax.swing.JTextField txtRegistroNombrePasajero;
    // End of variables declaration//GEN-END:variables
}
