package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorBusqueda;
import com.skyconnect.controlador.ControladorPasajeros;
import com.skyconnect.controlador.ControladorVuelo;
import com.skyconnect.modelo.Pasajero;
import com.skyconnect.modelo.Vuelo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class VueloIVUELTAView extends javax.swing.JPanel {

    private ControladorBusqueda controladorBusqueda;
    private ControladorPasajeros controladorPasajeros;
    private ArrayList<Vuelo> vuelosMostrados; // Para identificar qué vuelo se seleccionó
    
    /**
     * Creates new form VueloIVUELTAView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public VueloIVUELTAView(MainFrame mainFrame, ControladorBusqueda controladorBusqueda) {
        this.mainFrame = mainFrame;
        this.controladorBusqueda = controladorBusqueda;
        this.vuelosMostrados = new ArrayList<>();
        initComponents();
        java.net.URL imgURL = getClass().getResource("/imagenes/Vuelo.jpg");

        if (imgURL != null) {
            jLabelVUELTA.setIcon(new javax.swing.ImageIcon(imgURL));
        }
    }
    
    public void setControladorPasajeros(ControladorPasajeros controlador) {
        this.controladorPasajeros = controlador;
    }
    
    public void cargarDatosYBuscar() {
        //Crea un controlador para obtener el arreglo con todos los vuelos
        ControladorVuelo controlador = new ControladorVuelo();
        ArrayList<Vuelo> vuelos = controlador.obtenerVuelos();
        //Toma toda la lista de vuelos, pero solo devuelve y dibuja los que
        //nos interesa, o sea los seleccionados por el usuario
        mostrarVuelos(vuelos);
    }
    
    public void mostrarVuelos(ArrayList<Vuelo> todosLosVuelos) {
        limpiarCampos();
        vuelosMostrados.clear();
        //Controlador toma todos los vuelos y devuelve los 
        //que coinciden con lo que quiere el usuario
        ArrayList<Vuelo> vuelosFiltrados = controladorBusqueda.buscarVuelosVUELTA(todosLosVuelos);

        //La visa muestra los vuelos que son los que quiere el usuario
        for (int i = 0; i < vuelosFiltrados.size() && i < 3; i++) {
            Vuelo v = vuelosFiltrados.get(i);
            vuelosMostrados.add(v);
            switch (i) {
                case 0 -> cargarVuelo1(v);
                case 1 -> cargarVuelo2(v);
                case 2 -> cargarVuelo3(v);
            }
        }
    }
    
    private void seleccionarVuelo(int indice) {
        if (controladorPasajeros == null) {
            JOptionPane.showMessageDialog(this, "Error: No se han recibido datos de pasajeros.");
            return;
        }

        if (indice < vuelosMostrados.size()) {
            Vuelo vueloSeleccionado = vuelosMostrados.get(indice);

            // RECORRER PASAJEROS Y ASIGNAR DESCUENTOS SEGÚN EL DESTINO
            for (Pasajero p : controladorPasajeros.getListaPasajeros()) {
                ControladorPasajeros.asignarDescuento(p, vueloSeleccionado);
            }

            JOptionPane.showMessageDialog(this, "Vuelo seleccionado.");
            
            // Navegar a la siguiente pantalla de pago/resumen
            // mainFrame.mostrarVista("PAGO"); 
        }
    }
    
    //Metodos para que aparezcan los vuelos
    private void cargarVuelo1(Vuelo v) {
        txtFDestinoV1.setText(v.getRuta().getAeroLlegada().getCiudad());
        txtFFechaV1.setText(v.getFechaSalida());
        txtFDuracionV1.setText(v.getDuracion());
        txtFCostoV1.setText(String.valueOf(v.getPrecioEstimado()));
    }

    private void cargarVuelo2(Vuelo v) {
        txtFDestinoV2.setText(v.getRuta().getAeroLlegada().getCiudad());
        txtFFechaV2.setText(v.getFechaSalida());
        txtFDuracionV2.setText(v.getDuracion());
        txtFCostoV2.setText(String.valueOf(v.getPrecioEstimado()));
    }

    private void cargarVuelo3(Vuelo v) {
        txtFDestinoV3.setText(v.getRuta().getAeroLlegada().getCiudad());
        txtFFechaV3.setText(v.getFechaSalida());
        txtFDuracionV3.setText(v.getDuracion());
        txtFCostoV3.setText(String.valueOf(v.getPrecioEstimado()));
    }
    
    // Limpia
    private void limpiarCampos() {
        txtFDestinoV1.setText("");
        txtFFechaV1.setText("");
        txtFDuracionV1.setText("");
        txtFCostoV1.setText("");

        txtFDestinoV2.setText("");
        txtFFechaV2.setText("");
        txtFDuracionV2.setText("");
        txtFCostoV2.setText("");

        txtFDestinoV3.setText("");
        txtFFechaV3.setText("");
        txtFDuracionV3.setText("");
        txtFCostoV3.setText("");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnPredeterminadoGuayaquil = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFDestinoV1 = new javax.swing.JTextField();
        txtFFechaV1 = new javax.swing.JTextField();
        txtFDuracionV1 = new javax.swing.JTextField();
        txtFCostoV1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        radBtnSeleccionar1 = new javax.swing.JRadioButton();
        btnPredeterminadoGuayaquil1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtFDestinoV2 = new javax.swing.JTextField();
        txtFFechaV2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFDuracionV2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFCostoV2 = new javax.swing.JTextField();
        radBtnSeleccionar2 = new javax.swing.JRadioButton();
        btnPredeterminadoGuayaquil2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtFDestinoV3 = new javax.swing.JTextField();
        txtFFechaV3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFDuracionV3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFCostoV3 = new javax.swing.JTextField();
        radBtnSeleccionar3 = new javax.swing.JRadioButton();
        jLabelVUELTA = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel8.setText("Escoja su vuelo");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 348, -1));

        btnPredeterminadoGuayaquil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPredeterminadoGuayaquil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnPredeterminadoGuayaquil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 132, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Estimado VUELTA      ");
        btnPredeterminadoGuayaquil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        txtFDestinoV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestinoV1.setEnabled(false);
        txtFDestinoV1.addActionListener(this::txtFDestinoV1ActionPerformed);
        btnPredeterminadoGuayaquil.add(txtFDestinoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 18, 255, 46));

        txtFFechaV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFechaV1.setEnabled(false);
        txtFFechaV1.addActionListener(this::txtFFechaV1ActionPerformed);
        btnPredeterminadoGuayaquil.add(txtFFechaV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 70, 255, 50));

        txtFDuracionV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracionV1.setEnabled(false);
        txtFDuracionV1.setName(""); // NOI18N
        btnPredeterminadoGuayaquil.add(txtFDuracionV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 158, 48));

        txtFCostoV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCostoV1.setEnabled(false);
        txtFCostoV1.addActionListener(this::txtFCostoV1ActionPerformed);
        btnPredeterminadoGuayaquil.add(txtFCostoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 138, 119, 54));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("USD");
        btnPredeterminadoGuayaquil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 149, 45, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Duración:");
        btnPredeterminadoGuayaquil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnPredeterminadoGuayaquil.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, -1, 200));

        buttonGroup1.add(radBtnSeleccionar1);
        radBtnSeleccionar1.setText("Seleccionar");
        radBtnSeleccionar1.addActionListener(this::radBtnSeleccionar1ActionPerformed);
        btnPredeterminadoGuayaquil.add(radBtnSeleccionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jPanel3.add(btnPredeterminadoGuayaquil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 662, 210));

        btnPredeterminadoGuayaquil1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        txtFDestinoV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestinoV2.setEnabled(false);

        txtFFechaV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFechaV2.setEnabled(false);
        txtFFechaV2.addActionListener(this::txtFFechaV2ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Duración:");

        txtFDuracionV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracionV2.setEnabled(false);
        txtFDuracionV2.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Estimado VUELTA      ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("USD");

        txtFCostoV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCostoV2.setEnabled(false);
        txtFCostoV2.addActionListener(this::txtFCostoV2ActionPerformed);

        buttonGroup1.add(radBtnSeleccionar2);
        radBtnSeleccionar2.setText("Seleccionar");
        radBtnSeleccionar2.addActionListener(this::radBtnSeleccionar2ActionPerformed);

        javax.swing.GroupLayout btnPredeterminadoGuayaquil1Layout = new javax.swing.GroupLayout(btnPredeterminadoGuayaquil1);
        btnPredeterminadoGuayaquil1.setLayout(btnPredeterminadoGuayaquil1Layout);
        btnPredeterminadoGuayaquil1Layout.setHorizontalGroup(
            btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel12))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFDuracionV2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFDestinoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addComponent(txtFFechaV2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFCostoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(radBtnSeleccionar2))))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(487, Short.MAX_VALUE)))
        );
        btnPredeterminadoGuayaquil1Layout.setVerticalGroup(
            btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtFDestinoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFFechaV2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(txtFDuracionV2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(radBtnSeleccionar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFCostoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
            .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(btnPredeterminadoGuayaquil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, 220));

        btnPredeterminadoGuayaquil2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        txtFDestinoV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestinoV3.setEnabled(false);
        txtFDestinoV3.addActionListener(this::txtFDestinoV3ActionPerformed);

        txtFFechaV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFechaV3.setEnabled(false);
        txtFFechaV3.addActionListener(this::txtFFechaV3ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Duración:");

        txtFDuracionV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracionV3.setEnabled(false);
        txtFDuracionV3.setName(""); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Estimado VUELTA     ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("USD");

        txtFCostoV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCostoV3.setEnabled(false);
        txtFCostoV3.addActionListener(this::txtFCostoV3ActionPerformed);

        buttonGroup1.add(radBtnSeleccionar3);
        radBtnSeleccionar3.setText("Seleccionar");
        radBtnSeleccionar3.addActionListener(this::radBtnSeleccionar3ActionPerformed);

        javax.swing.GroupLayout btnPredeterminadoGuayaquil2Layout = new javax.swing.GroupLayout(btnPredeterminadoGuayaquil2);
        btnPredeterminadoGuayaquil2.setLayout(btnPredeterminadoGuayaquil2Layout);
        btnPredeterminadoGuayaquil2Layout.setHorizontalGroup(
            btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFFechaV3)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFDuracionV3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFDestinoV3))
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFCostoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radBtnSeleccionar3)
                        .addGap(15, 15, 15))))
            .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(485, Short.MAX_VALUE)))
        );
        btnPredeterminadoGuayaquil2Layout.setVerticalGroup(
            btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFFechaV3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radBtnSeleccionar3))
                .addGap(10, 10, 10)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addComponent(txtFDestinoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFDuracionV3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFCostoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );

        jPanel3.add(btnPredeterminadoGuayaquil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 662, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 1050, 980));

        jLabelVUELTA.setIcon(new javax.swing.ImageIcon("C:\\Users\\vemom\\Documents\\NetBeansProjects\\SkyConnect\\src\\main\\java\\resources\\imagenes\\Vuelo.jpg")); // NOI18N
        jLabelVUELTA.setText("jLabel13");
        jPanel1.add(jLabelVUELTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFFechaV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaV1ActionPerformed

    private void txtFCostoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCostoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCostoV1ActionPerformed

    private void txtFFechaV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaV2ActionPerformed

    private void txtFCostoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCostoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCostoV2ActionPerformed

    private void txtFFechaV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaV3ActionPerformed

    private void txtFCostoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCostoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCostoV3ActionPerformed

    private void txtFDestinoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDestinoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDestinoV1ActionPerformed

    private void txtFDestinoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDestinoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDestinoV3ActionPerformed

    private void radBtnSeleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnSeleccionar1ActionPerformed
        // TODO add your handling code here:
        seleccionarVuelo(0);
    }//GEN-LAST:event_radBtnSeleccionar1ActionPerformed

    private void radBtnSeleccionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnSeleccionar2ActionPerformed
        // TODO add your handling code here:
        seleccionarVuelo(1);
    }//GEN-LAST:event_radBtnSeleccionar2ActionPerformed

    private void radBtnSeleccionar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnSeleccionar3ActionPerformed
        // TODO add your handling code here:
        seleccionarVuelo(2);
    }//GEN-LAST:event_radBtnSeleccionar3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPredeterminadoGuayaquil;
    private javax.swing.JPanel btnPredeterminadoGuayaquil1;
    private javax.swing.JPanel btnPredeterminadoGuayaquil2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelVUELTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton radBtnSeleccionar1;
    private javax.swing.JRadioButton radBtnSeleccionar2;
    private javax.swing.JRadioButton radBtnSeleccionar3;
    private javax.swing.JTextField txtFCostoV1;
    private javax.swing.JTextField txtFCostoV2;
    private javax.swing.JTextField txtFCostoV3;
    private javax.swing.JTextField txtFDestinoV1;
    private javax.swing.JTextField txtFDestinoV2;
    private javax.swing.JTextField txtFDestinoV3;
    private javax.swing.JTextField txtFDuracionV1;
    private javax.swing.JTextField txtFDuracionV2;
    private javax.swing.JTextField txtFDuracionV3;
    private javax.swing.JTextField txtFFechaV1;
    private javax.swing.JTextField txtFFechaV2;
    private javax.swing.JTextField txtFFechaV3;
    // End of variables declaration//GEN-END:variables
}
