package com.skyconnect.vista;

import com.skyconnect.modelo.Vuelo;
import java.util.List;

public class VueloIVUELTAView extends javax.swing.JPanel {

    /**
     * Creates new form VueloIVUELTAView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public VueloIVUELTAView(MainFrame mainFrame) {
        this.mainFrame = mainFrame; 
        initComponents();
    }
    
    /**
    * Muestra hasta 3 vuelos de vuelta en la interfaz.
    * La vista solo se encarga de presentar los datos.
    */
    public void mostrarVuelosVuelta(List<Vuelo> vuelos) {
        if (vuelos == null || vuelos.isEmpty()) {
        return;
            }

        if (vuelos.size() > 0) {
            cargarVuelo(vuelos.get(0), 
                txtFDestinoV1, txtFFechaV1, txtFDuracionV1, txtFCostoV1);
        }

        if (vuelos.size() > 1) {
            cargarVuelo(vuelos.get(1), 
                txtFDestinoV2, txtFFechaV2, txtFDuracionV2, txtFCostoV2);
        }

        if (vuelos.size() > 2) {
            cargarVuelo(vuelos.get(2), 
                txtFDestinoV3, txtFFechaV3, txtFDuracionV3, txtFCostoV3);
        }
    }
    /**
 * Carga la información de un vuelo en los campos visuales.
 */
    private void cargarVuelo(
           Vuelo v,
           javax.swing.JTextField destino,
           javax.swing.JTextField fecha,
           javax.swing.JTextField duracion,
           javax.swing.JTextField costo) {
        destino.setText(v.getRuta().getAeroLlegada().getCiudad());
        fecha.setText(v.getFechaSalida().toString());
        duracion.setText(v.getDuracion().toString());
        costo.setText(String.valueOf(v.getPrecioEstimado()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnPredeterminadoGuayaquil = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFDestinoV1 = new javax.swing.JTextField();
        txtFFechaV1 = new javax.swing.JTextField();
        txtFDuracionV1 = new javax.swing.JTextField();
        txtFCostoV1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnPredeterminadoGuayaquil1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtFDestinoV2 = new javax.swing.JTextField();
        txtFFechaV2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFDuracionV2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFCostoV2 = new javax.swing.JTextField();
        btnPredeterminadoGuayaquil2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtFDestinoV3 = new javax.swing.JTextField();
        txtFFechaV3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFDuracionV3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFCostoV3 = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel8.setText("Escoja su vuelo");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 6, 348, -1));

        btnPredeterminadoGuayaquil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPredeterminadoGuayaquil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnPredeterminadoGuayaquil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 132, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Estimado VUELTA      ");
        btnPredeterminadoGuayaquil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        txtFDestinoV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestinoV1.setEnabled(false);
        txtFDestinoV1.addActionListener(this::txtFDestinoV1ActionPerformed);
        btnPredeterminadoGuayaquil.add(txtFDestinoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 18, 255, 46));

        txtFFechaV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFechaV1.setEnabled(false);
        txtFFechaV1.addActionListener(this::txtFFechaV1ActionPerformed);
        btnPredeterminadoGuayaquil.add(txtFFechaV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 70, 255, 50));

        txtFDuracionV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracionV1.setEnabled(false);
        txtFDuracionV1.setName(""); // NOI18N
        btnPredeterminadoGuayaquil.add(txtFDuracionV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 158, 48));

        txtFCostoV1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCostoV1.setEnabled(false);
        txtFCostoV1.addActionListener(this::txtFCostoV1ActionPerformed);
        btnPredeterminadoGuayaquil.add(txtFCostoV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 138, 119, 54));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("USD");
        btnPredeterminadoGuayaquil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 149, 45, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Duración:");
        btnPredeterminadoGuayaquil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnPredeterminadoGuayaquil.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, -1, 200));

        jPanel3.add(btnPredeterminadoGuayaquil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 662, 210));

        btnPredeterminadoGuayaquil1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        txtFDestinoV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestinoV2.setEnabled(false);

        txtFFechaV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFechaV2.setEnabled(false);
        txtFFechaV2.addActionListener(this::txtFFechaV2ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Duración:");

        txtFDuracionV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracionV2.setEnabled(false);
        txtFDuracionV2.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Estimado VUELTA      ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("USD");

        txtFCostoV2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCostoV2.setEnabled(false);
        txtFCostoV2.addActionListener(this::txtFCostoV2ActionPerformed);

        javax.swing.GroupLayout btnPredeterminadoGuayaquil1Layout = new javax.swing.GroupLayout(btnPredeterminadoGuayaquil1);
        btnPredeterminadoGuayaquil1.setLayout(btnPredeterminadoGuayaquil1Layout);
        btnPredeterminadoGuayaquil1Layout.setHorizontalGroup(
            btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel12))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFDuracionV2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFDestinoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addComponent(txtFFechaV2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFCostoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(481, Short.MAX_VALUE)))
        );
        btnPredeterminadoGuayaquil1Layout.setVerticalGroup(
            btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFCostoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtFDestinoV2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFFechaV2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(txtFDuracionV2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
            .addGroup(btnPredeterminadoGuayaquil1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoGuayaquil1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(btnPredeterminadoGuayaquil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 220));

        btnPredeterminadoGuayaquil2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        txtFDestinoV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestinoV3.setEnabled(false);
        txtFDestinoV3.addActionListener(this::txtFDestinoV3ActionPerformed);

        txtFFechaV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFechaV3.setEnabled(false);
        txtFFechaV3.addActionListener(this::txtFFechaV3ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Duración:");

        txtFDuracionV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracionV3.setEnabled(false);
        txtFDuracionV3.setName(""); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Estimado VUELTA     ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("USD");

        txtFCostoV3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCostoV3.setEnabled(false);
        txtFCostoV3.addActionListener(this::txtFCostoV3ActionPerformed);

        javax.swing.GroupLayout btnPredeterminadoGuayaquil2Layout = new javax.swing.GroupLayout(btnPredeterminadoGuayaquil2);
        btnPredeterminadoGuayaquil2.setLayout(btnPredeterminadoGuayaquil2Layout);
        btnPredeterminadoGuayaquil2Layout.setHorizontalGroup(
            btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFFechaV3)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFDuracionV3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFDestinoV3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFCostoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        btnPredeterminadoGuayaquil2Layout.setVerticalGroup(
            btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtFFechaV3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addComponent(txtFDestinoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtFDuracionV3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFCostoV3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(btnPredeterminadoGuayaquil2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoGuayaquil2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );

        jPanel3.add(btnPredeterminadoGuayaquil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 662, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFFechaV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaV1ActionPerformed

    private void txtFCostoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCostoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCostoV1ActionPerformed

    private void txtFFechaV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaV2ActionPerformed

    private void txtFCostoV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCostoV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCostoV2ActionPerformed

    private void txtFFechaV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaV3ActionPerformed

    private void txtFCostoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCostoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCostoV3ActionPerformed

    private void txtFDestinoV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDestinoV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDestinoV1ActionPerformed

    private void txtFDestinoV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDestinoV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDestinoV3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPredeterminadoGuayaquil;
    private javax.swing.JPanel btnPredeterminadoGuayaquil1;
    private javax.swing.JPanel btnPredeterminadoGuayaquil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtFCostoV1;
    private javax.swing.JTextField txtFCostoV2;
    private javax.swing.JTextField txtFCostoV3;
    private javax.swing.JTextField txtFDestinoV1;
    private javax.swing.JTextField txtFDestinoV2;
    private javax.swing.JTextField txtFDestinoV3;
    private javax.swing.JTextField txtFDuracionV1;
    private javax.swing.JTextField txtFDuracionV2;
    private javax.swing.JTextField txtFDuracionV3;
    private javax.swing.JTextField txtFFechaV1;
    private javax.swing.JTextField txtFFechaV2;
    private javax.swing.JTextField txtFFechaV3;
    // End of variables declaration//GEN-END:variables
}
