package com.skyconnect.vista;

import com.skyconnect.controlador.ControladorVuelo;
import com.skyconnect.modelo.Vuelo;
import java.util.List;

public class VueloIDAView extends javax.swing.JPanel {
    /**
     * Creates new form VueloIDAView
     */
    private MainFrame mainFrame; 
    // Constructor que inicializa la vista y permite la navegación entre pantallas
    // a través del MainFrame usando CardLayout.
    public VueloIDAView(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        // Solicita los vuelos al controlador
        ControladorVuelo controlador = new ControladorVuelo();
        List<Vuelo> vuelos = controlador.obtenerVuelos();

        // Muestra los vuelos en la vista
        mostrarVuelos(vuelos);
    }
    

    //Muestra hasta 3 vuelos en los paneles de la vista.
    public void mostrarVuelos(List<Vuelo> vuelos) {
        limpiarCampos();

        for (int i = 0; i < vuelos.size() && i < 3; i++) {
            Vuelo v = vuelos.get(i);
            switch (i) {
                case 0 -> cargarVuelo1(v);
                case 1 -> cargarVuelo2(v);
                case 2 -> cargarVuelo3(v);
            }
        }
    }
    //Metodos para que aparezcan los vuelos predeterminados 
    private void cargarVuelo1(Vuelo v) {
    txtFDestino1.setText(v.getRuta().getAeroLlegada().getCiudad());
    txtFFecha1.setText(v.getFechaSalida().toString());
    txtFDuracion1.setText(v.getDuracion().toString());
    txtFCosto1.setText(String.valueOf(v.getPrecioEstimado()));
    }

    private void cargarVuelo2(Vuelo v) {
    txtFDestino2.setText(v.getRuta().getAeroLlegada().getCiudad());
    txtFFecha2.setText(v.getFechaSalida().toString());
    txtFDuracion2.setText(v.getDuracion().toString());
    txtFCosto2.setText(String.valueOf(v.getPrecioEstimado()));
    }

    private void cargarVuelo3(Vuelo v) {
    txtFDestino3.setText(v.getRuta().getAeroLlegada().getCiudad());
    txtFFecha3.setText(v.getFechaSalida().toString());
    txtFDuracion3.setText(v.getDuracion().toString());
    txtFCosto3.setText(String.valueOf(v.getPrecioEstimado()));
    }
    // Limpia
    private void limpiarCampos() {
    txtFDestino1.setText("");
    txtFFecha1.setText("");
    txtFDuracion1.setText("");
    txtFCosto1.setText("");

    txtFDestino2.setText("");
    txtFFecha2.setText("");
    txtFDuracion2.setText("");
    txtFCosto2.setText("");

    txtFDestino3.setText("");
    txtFFecha3.setText("");
    txtFDuracion3.setText("");
    txtFCosto3.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnPredeterminadoVuelo1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFDestino1 = new javax.swing.JTextField();
        txtFFecha1 = new javax.swing.JTextField();
        txtFDuracion1 = new javax.swing.JTextField();
        txtFCosto1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPredeterminadoVuelo2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtFDestino2 = new javax.swing.JTextField();
        txtFFecha2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFDuracion2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFCosto2 = new javax.swing.JTextField();
        btnPredeterminadoVuelo3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtFDestino3 = new javax.swing.JTextField();
        txtFFecha3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFDuracion3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFCosto3 = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel8.setText("Escoja su vuelo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 348, 50));

        btnPredeterminadoVuelo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Estimado IDA       ");

        txtFDestino1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestino1.setEnabled(false);
        txtFDestino1.addActionListener(this::txtFDestino1ActionPerformed);

        txtFFecha1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFecha1.setEnabled(false);
        txtFFecha1.addActionListener(this::txtFFecha1ActionPerformed);

        txtFDuracion1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracion1.setEnabled(false);
        txtFDuracion1.setName(""); // NOI18N

        txtFCosto1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCosto1.setEnabled(false);
        txtFCosto1.addActionListener(this::txtFCosto1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("USD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Duración:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnPredeterminadoVuelo1Layout = new javax.swing.GroupLayout(btnPredeterminadoVuelo1);
        btnPredeterminadoVuelo1.setLayout(btnPredeterminadoVuelo1Layout);
        btnPredeterminadoVuelo1Layout.setHorizontalGroup(
            btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                        .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFDuracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFCosto1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPredeterminadoVuelo1Layout.setVerticalGroup(
            btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtFDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtFFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(btnPredeterminadoVuelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFCosto1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo1Layout.createSequentialGroup()
                                .addComponent(txtFDuracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addContainerGap())
        );

        btnPredeterminadoVuelo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtFDestino2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDestino2.setEnabled(false);
        txtFDestino2.addActionListener(this::txtFDestino2ActionPerformed);

        txtFFecha2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFFecha2.setEnabled(false);
        txtFFecha2.addActionListener(this::txtFFecha2ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Duración:");

        txtFDuracion2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracion2.setEnabled(false);
        txtFDuracion2.setName(""); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Estimado IDA       ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("USD");

        txtFCosto2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCosto2.setEnabled(false);
        txtFCosto2.addActionListener(this::txtFCosto2ActionPerformed);

        javax.swing.GroupLayout btnPredeterminadoVuelo2Layout = new javax.swing.GroupLayout(btnPredeterminadoVuelo2);
        btnPredeterminadoVuelo2.setLayout(btnPredeterminadoVuelo2Layout);
        btnPredeterminadoVuelo2Layout.setHorizontalGroup(
            btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel12)
                .addGap(95, 95, 95)
                .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                        .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFFecha2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtFDestino2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo2Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(164, 164, 164)
                        .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFCosto2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
            .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(118, 118, 118)
                    .addComponent(txtFDuracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );
        btnPredeterminadoVuelo2Layout.setVerticalGroup(
            btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtFDestino2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtFFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFCosto2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo2Layout.createSequentialGroup()
                    .addGroup(btnPredeterminadoVuelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                            .addContainerGap(131, Short.MAX_VALUE)
                            .addComponent(txtFDuracion2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23))
                        .addGroup(btnPredeterminadoVuelo2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        btnPredeterminadoVuelo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtFDestino3.setEnabled(false);

        txtFFecha3.setEnabled(false);
        txtFFecha3.addActionListener(this::txtFFecha3ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Duración:");

        txtFDuracion3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFDuracion3.setEnabled(false);
        txtFDuracion3.setName(""); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Estimado IDA       ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setText("USD");

        txtFCosto3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtFCosto3.setEnabled(false);
        txtFCosto3.addActionListener(this::txtFCosto3ActionPerformed);

        javax.swing.GroupLayout btnPredeterminadoVuelo3Layout = new javax.swing.GroupLayout(btnPredeterminadoVuelo3);
        btnPredeterminadoVuelo3.setLayout(btnPredeterminadoVuelo3Layout);
        btnPredeterminadoVuelo3Layout.setHorizontalGroup(
            btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(32, 32, 32))
            .addGroup(btnPredeterminadoVuelo3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel18)
                .addGap(101, 101, 101)
                .addGroup(btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(btnPredeterminadoVuelo3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFDuracion3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addComponent(txtFDestino3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(txtFFecha3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFCosto3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPredeterminadoVuelo3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(469, Short.MAX_VALUE)))
        );
        btnPredeterminadoVuelo3Layout.setVerticalGroup(
            btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPredeterminadoVuelo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFDestino3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoVuelo3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(btnPredeterminadoVuelo3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtFFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPredeterminadoVuelo3Layout.createSequentialGroup()
                        .addGroup(btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFCosto3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo3Layout.createSequentialGroup()
                        .addGroup(btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFDuracion3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20))))
            .addGroup(btnPredeterminadoVuelo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPredeterminadoVuelo3Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPredeterminadoVuelo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPredeterminadoVuelo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPredeterminadoVuelo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(524, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPredeterminadoVuelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPredeterminadoVuelo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPredeterminadoVuelo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 1180, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFFecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFecha1ActionPerformed

    private void txtFCosto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCosto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCosto1ActionPerformed

    private void txtFFecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFecha2ActionPerformed

    private void txtFCosto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCosto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCosto2ActionPerformed

    private void txtFFecha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFecha3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFecha3ActionPerformed

    private void txtFCosto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCosto3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFCosto3ActionPerformed

    private void txtFDestino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDestino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDestino1ActionPerformed

    private void txtFDestino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFDestino2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFDestino2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPredeterminadoVuelo1;
    private javax.swing.JPanel btnPredeterminadoVuelo2;
    private javax.swing.JPanel btnPredeterminadoVuelo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtFCosto1;
    private javax.swing.JTextField txtFCosto2;
    private javax.swing.JTextField txtFCosto3;
    private javax.swing.JTextField txtFDestino1;
    private javax.swing.JTextField txtFDestino2;
    private javax.swing.JTextField txtFDestino3;
    private javax.swing.JTextField txtFDuracion1;
    private javax.swing.JTextField txtFDuracion2;
    private javax.swing.JTextField txtFDuracion3;
    private javax.swing.JTextField txtFFecha1;
    private javax.swing.JTextField txtFFecha2;
    private javax.swing.JTextField txtFFecha3;
    // End of variables declaration//GEN-END:variables
}
